### ISSUE TITLE
tar_options(debug = "targetname") doesn't work - it needs tar_options(debug = "targetname_subtargethash")

### ISSUE THREAD

**Issue by kendonB** [wlandau/targets#122]
## Prework

* [x] I understand and agree to `targets`' [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to `targets`' [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] I am reasonably sure this is a genuine bug in `targets` and most likely not a user error. (If you run into an error and do not know the cause, please submit a "Trouble" issue instead.)
* [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

I am trying out debugging here: https://wlandau.github.io/targets-manual/practice.html and found that using a dynamic target name did not work. I had to put in the subtarget name. I would have expected the first subtarget to debug if putting the dynamic target name in for debugging.

## Reproducible example

The `targets` package setup makes this hard within `reprex` - might be good to provide a template that works within `reprex` if you can figure that out?

```r
library(targets)

tar_options(packages = c("tidyverse"))
tar_options(debug = "dynamic")

tar_pipeline(
  tar_target(
    x,
    1:2
  ),
  tar_target(
    dynamic,
    x + 1,
    pattern = map(x)
  )
)
```
## Expected result

It should have debugged.

**Comment by wlandau** [comment]
Should work now. I was originally thinking the primary use case would be individual branches, but now that you bring it up, entire patterns also help.
