### ISSUE TITLE
List of features removed from drake?

### ISSUE THREAD

**Issue by kendonB** [wlandau/targets#123]
## Prework

* [x] I understand and agree to `targets`' [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to `targets`' [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

One thing that would help me with adoption is to be able to refer to a list of `drake` features that are not present in `targets`. These could be split into active decisions like removing `ignore` and features that just are yet to be implemented. 

My learning workflow is to say "how do you do X in targets?" then Ctrl-F the manual or browse function names. Knowing whether such an effort will be successful in advance will speed this along substantially I think. This would also help people know in advance if they want to switch at all.

**Comment by mattwarkentin** [comment]
I'll just jump on this train...

Is `tar_meta()` meant to serve as the replacement for `drake::cached()`?

**Comment by wlandau** [comment]
Thank you both. @kendonB, I think the function correspondence table at https://wlandau.github.io/targets-manual/index.html#what-about-drake gets us most of the way there. We can add rows for `drake` functions not supported in `targets` and point to workarounds.

@mattwarkentin, yes, the `name` column of `tar_meta()` includes the same information as `drake::cached()` (although they do handle edge cases a bit differently).

**Comment by wlandau** [comment]
Fixed in https://github.com/wlandau/targets-manual/commit/7b7d91efb3f2de0ae73e7e0c720e9560d70c2675.
