### ISSUE TITLE
Capture messages in a column in tar_meta() for remotely built targets

### ISSUE THREAD

**Issue by mattwarkentin** [wlandau/targets#124]
## Prework

* [x] I understand and agree to `targets`' [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to `targets`' [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

When using `tar_make_clustermq()` on a HPC with `options(clustermq.scheduler="slurm")` messages, warnings, and/or errors aren't printed to the console in the master process. I am actually fine with this and it is probably the sensible choice, but I was wondering if it would be worthwhile to capture `message()`s in a column in `tar_meta()` similar to how warnings and errors are captured. 

When instead using `options(clustermq.scheduler="multicore")`, messages __are__ printed in the master process, but warnings and errors are not, and are only captured in `tar_meta()`.

**Comment by wlandau** [comment]
Good question, people have certainly asked for this in `drake`. My preference right now is to keep messages out of `tar_meta()` for the sake of performance. `_targets/meta/meta` has no compression, so if users print a lot of messages (e.g. with custom progress bars within targets) it could down `tar_make()` and friends. A few possible workarounds:

* Invoke a logging package such as `futile.logger` in your custom code. 
* `tar_make_future()` with https://github.com/ropensci/drake/issues/400#issuecomment-586395816.
* Revive https://github.com/mschubert/clustermq/issues/21.

**Comment by mattwarkentin** [comment]
That's fair. I have often used `{log4r}` when explicit logging is needed. Similarly, one can easily use Slurm's native logging with `#SBATCH --output=...` in the template file.

**Comment by wlandau** [comment]
Just reverted #125 in favor of commits e211d97deb5042fa625131873384db31c5582a06 through 4fb4dd1693e68ab76860878b8b5cdb1b90ed0991. Manual relaying can duplicate messages, and the new approach just points users to targets that threw warnings.

**Comment by mattwarkentin** [comment]
> Surprised you do not see errors.

I am now thinking perhaps I did not check whether errors were propagated. Might have only checked messages and warnings.

I look forward to testing out these new commits.

**Comment by mattwarkentin** [comment]
So I may be getting too bogged down in edge cases here, but since messages are swallowed by the master process, if you use `tryCatch()` for condition handling to return informative error messages, they won't be flagged by the master OR available in `tar_meta()`. This is the expected behaviour but I'm wondering if its problematic at all.

I modified the example from [here](http://adv-r.had.co.nz/Exceptions-Debugging.html).
```r
# _targets.R

library(targets)

show_condition <- function(code) {
  tryCatch(code,
    error = function(c) "error",
    warning = function(c) "warning",
    message = function(c) "message"
  )
}

options(
  clustermq.scheduler = "multicore"
)

tar_pipeline(
  tar_target(
    ttt,
    show_condition(stop()),
    format = "qs"
  )
)
```
```
● 2020-07-21 12:11:06.20 -0400 GMT run target ttt
Master: [5.0s 9.8% CPU]; Worker: [avg 20.4% CPU, max 2430770.0 Mb]
```

Not sure what exactly to do with this information...

**Comment by wlandau** [comment]
Yeah, that's a cool trick. `targets` actually does something similar to capture/relay warnings and error messages. `tryCatch()` or `withCallingHandlers()` in your custom code could allow you to take manual control of messages.

https://github.com/wlandau/targets/blob/4fb4dd1693e68ab76860878b8b5cdb1b90ed0991/R/class_build.R#L3-L27
