### ISSUE TITLE
Allow for named-lists when using list-aggregation on the results from group iteration

### ISSUE THREAD

**Issue by mattwarkentin** [wlandau/targets#126]
## Prework

* [x] I understand and agree to `targets`' [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to `targets`' [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Hi @wlandau,

I hope you aren't yet tired of hearing from me. I have been playing around with the new `iteration = "group"` / `tar_group()` feature, and also using `iteration = "list"` for aggregation. It is great, and makes parallelizing within a data set quite simple. I don't really know what the best choice would be for how to implement this idea, but I was wondering if it would be possible to have the aggregate list to be a named list, rather than just index 1 though N.

Here is a simple example, where it would be nice if the list, when read in by `tar_read()`, was a named list. 

```r
library(targets)

tar_script({
  tar_options(packages = c("tidyverse", "gapminder"))
  tar_pipeline(
    tar_target(
      gap,
      gapminder %>% group_by(continent) %>% tar_group(),
      iteration = "group"
      ),
    tar_target(
      models,
      lm(lifeExp ~ year, data = gap),
      pattern = map(gap),
      iteration = "list"
      )
    )
  })

tar_make()
```

```r
tar_read(models)
```
```
[[1]]

Call:
lm(formula = lifeExp ~ year, data = gap)

Coefficients:
(Intercept)         year  
  -524.2578       0.2895  


[[2]]

Call:
lm(formula = lifeExp ~ year, data = gap)

Coefficients:
(Intercept)         year  
  -663.1063       0.3677  


[[3]]

Call:
lm(formula = lifeExp ~ year, data = gap)

Coefficients:
(Intercept)         year  
  -836.8909       0.4531  


[[4]]

Call:
lm(formula = lifeExp ~ year, data = gap)

Coefficients:
(Intercept)         year  
  -367.4110       0.2219  


[[5]]

Call:
lm(formula = lifeExp ~ year, data = gap)

Coefficients:
(Intercept)         year  
  -341.9080       0.2103
```

Perhaps `tar_group()` could have an extra argument for forming meaningful names, rather than just integer group indices. Or maybe it could use `dplyr::group_keys()` and `dplyr::group_vars()` to paste together meaningful names. Maybe `tar_group(x, named_list = TRUE)`...

```r
# hacky example
gdf <- 
  gapminder %>% 
  group_by(continent, country) %>% 
  tar_group()

gdf %>% 
  group_keys() %>% 
  transmute(names = paste(!!!syms(group_vars(gdf)), sep = "_")) %>% 
  pull(names)
```
```
 [1] "Africa_Algeria"                 
 [2] "Africa_Angola"                  
 [3] "Africa_Benin"                   
 [4] "Africa_Botswana"                
 [5] "Africa_Burkina Faso"            
 [6] "Africa_Burundi"                 
 [7] "Africa_Cameroon"                
 [8] "Africa_Central African Republic"
 [9] "Africa_Chad"                    
[10] "Africa_Comoros"                 
 [ reached getOption("max.print") -- omitted 132 entries ]
```

Side question: Have you thought about providing aggregation support via `rbind()`/`bind_rows()` or `cbind()`/`bind_cols()` in addition to `vec_c()` and `list()`?

**Comment by mattwarkentin** [comment]
I suppose this could apply equally to `vec_c()` and not just `list()`. A named vector might be nice too, when using `"vector"` aggregation on the results from grouped iterations.

**Comment by wlandau** [comment]
> I hope you aren't yet tired of hearing from me.

Nope, you've helped out a lot so far! Please keep the feedback coming as long as you still feel like it.

>  I was wondering if it would be possible to have the aggregate list to be a named list, rather than just index 1 though N.

For `drake`, I tried to get into this territory with names in static branching and the "trace" in dynamic branching. Automated names got really big and confusing, and the technical debt it took to make it useful turned out to not be worth it. For `targets`, I think things could get out of hand easily because branch names have cryptic hashes, and if you `map()` or `cross()` over multiple targets, those names are going to get really long. At the risk of rigidness and inconvenience, I would prefer to draw a clear line and not support names. 

But on the bright side, the workarounds on the user's end are usually straightforward, especially if you embrace the `tidyverse`.

``` r
library(targets)

tar_script({
  tar_options(packages = c("tidyverse", "gapminder", "broom"))
  options(crayon.enabled = FALSE, tidyverse.quiet = TRUE)
  tar_pipeline(
    tar_target(
      gap,
      gapminder %>% group_by(continent) %>% tar_group(),
      iteration = "group"
    ),
    tar_target(
      models,
      lm(lifeExp ~ year, data = gap) %>%
        broom::tidy() %>%
        filter(term == "year") %>%
        mutate(contenent = gap$continent[1]),
      pattern = map(gap)
    )
  )
})

tar_make()
#> ● run target gap
#> ● run branch models_2b4b7950
#> ● run branch models_d4cd5260
#> ● run branch models_b280960a
#> ● run branch models_66bd998d
#> ● run branch models_6e15f911

tar_read(models)
#> # A tibble: 5 x 6
#>   term  estimate std.error statistic  p.value contenent
#>   <chr>    <dbl>     <dbl>     <dbl>    <dbl> <fct>    
#> 1 year     0.290   0.0178       16.3 6.78e-50 Africa   
#> 2 year     0.368   0.0230       16.0 4.35e-42 Americas 
#> 3 year     0.453   0.0260       17.4 6.92e-51 Asia     
#> 4 year     0.222   0.0118       18.9 1.34e-55 Europe   
#> 5 year     0.210   0.00984      21.4 3.30e-16 Oceania
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
> Side question: Have you thought about providing aggregation support via rbind()/bind_rows() or cbind()/bind_cols() in addition to vec_c() and list()?

One of the magical things about `vec_c()` is that it already binds the rows if you give it data frames.

``` r
library(tibble)
library(vctrs)
d1 <- tibble(x = 1, y = 2)
d2 <- tibble(x = 3, y = 4)
vec_c(d1, d2)
#> # A tibble: 2 x 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
#> 2     3     4
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattwarkentin** [comment]
All of what you said makes total sense. I could see how it could get out of hand quickly, especially with crossing. I'll keep throwing out ideas until a good one lands!

> One of the magical things about `vec_c()` is that it already binds the rows if you give it data frames.

Oh, perfect! I didn't realize that was how `vec_c()` handled data frames. That is definitely good to know.

Maybe something could be added to the `tar_group()` or `tar_target()` documentation (unless it exists and I just missed it) to make this clear, since I think most people are used to how `c()` works, and not `vec_c()`. Something like:

> If the return value of a target is a data frame, then `"vector"` aggregation by `vec_c()` will bind the data frames by row, similar to `rbind()` or `bind_rows()`.

**Comment by mattwarkentin** [comment]
Also, while I'm in weeds here, it might be worth noting in the documentation that the combination of `group_by()` and `tar_group()` assign indices based on ascending alphabetic or numeric order, and not on how the data is naturally ordered in the data sets.

```r
gapminder %>% 
  group_by(continent) %>% 
  tar_group()
```
```
# A tibble: 1,704 x 7
# Groups:   continent [5]
   country    continent  year lifeExp     pop gdpPercap tar_group
   <fct>      <fct>     <int>   <dbl>   <int>     <dbl>     <int>
 1 Afghanist… Asia       1952    28.8  8.43e6      779.         3
 2 Afghanist… Asia       1957    30.3  9.24e6      821.         3
 3 Afghanist… Asia       1962    32.0  1.03e7      853.         3
 4 Afghanist… Asia       1967    34.0  1.15e7      836.         3
 5 Afghanist… Asia       1972    36.1  1.31e7      740.         3
 6 Afghanist… Asia       1977    38.4  1.49e7      786.         3
 7 Afghanist… Asia       1982    39.9  1.29e7      978.         3
 8 Afghanist… Asia       1987    40.8  1.39e7      852.         3
 9 Afghanist… Asia       1992    41.7  1.63e7      649.         3
10 Afghanist… Asia       1997    41.8  2.22e7      635.         3
# … with 1,694 more rows
```

```r
gapminder %>% 
  group_by(lifeExp) %>% 
  tar_group()
```
```
# A tibble: 1,704 x 7
# Groups:   lifeExp [1,626]
   country    continent  year lifeExp     pop gdpPercap tar_group
   <fct>      <fct>     <int>   <dbl>   <int>     <dbl>     <int>
 1 Afghanist… Asia       1952    28.8  8.43e6      779.         2
 2 Afghanist… Asia       1957    30.3  9.24e6      821.         6
 3 Afghanist… Asia       1962    32.0  1.03e7      853.        11
 4 Afghanist… Asia       1967    34.0  1.15e7      836.        25
 5 Afghanist… Asia       1972    36.1  1.31e7      740.        45
 6 Afghanist… Asia       1977    38.4  1.49e7      786.        83
 7 Afghanist… Asia       1982    39.9  1.29e7      978.       114
 8 Afghanist… Asia       1987    40.8  1.39e7      852.       152
 9 Afghanist… Asia       1992    41.7  1.63e7      649.       172
10 Afghanist… Asia       1997    41.8  2.22e7      635.       176
# … with 1,694 more rows
```

**Comment by wlandau** [comment]
I see what you mean. Row order is unpredictable, so I think it's the right call.

``` r
suppressPackageStartupMessages(library(dplyr))
library(gapminder)
library(targets)

x <- gapminder %>%
  group_by(continent) %>%
  group_modify(~head(.x, 1)) %>%
  ungroup()

x %>%
  arrange(continent) %>%
  group_by(continent) %>%
  tar_group()
#> # A tibble: 5 x 7
#> # Groups:   continent [5]
#>   continent country      year lifeExp      pop gdpPercap tar_group
#>   <fct>     <fct>       <int>   <dbl>    <int>     <dbl>     <int>
#> 1 Africa    Algeria      1952    43.1  9279525     2449.         1
#> 2 Americas  Argentina    1952    62.5 17876956     5911.         2
#> 3 Asia      Afghanistan  1952    28.8  8425333      779.         3
#> 4 Europe    Albania      1952    55.2  1282697     1601.         4
#> 5 Oceania   Australia    1952    69.1  8691212    10040.         5

x %>%
  arrange(desc(continent)) %>%
  group_by(continent) %>%
  tar_group()
#> # A tibble: 5 x 7
#> # Groups:   continent [5]
#>   continent country      year lifeExp      pop gdpPercap tar_group
#>   <fct>     <fct>       <int>   <dbl>    <int>     <dbl>     <int>
#> 1 Oceania   Australia    1952    69.1  8691212    10040.         5
#> 2 Europe    Albania      1952    55.2  1282697     1601.         4
#> 3 Asia      Afghanistan  1952    28.8  8425333      779.         3
#> 4 Americas  Argentina    1952    62.5 17876956     5911.         2
#> 5 Africa    Algeria      1952    43.1  9279525     2449.         1
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattwarkentin** [comment]
I agree, row order is unpredictable so I think the heuristic of using ascending alphanumeric order to start indexing groups is probably the right call.

I just think its important for users to know that group jobs are done in index order, and the value loaded by `tar_read()`/`tar_load()` is in index order.

Something like the following code _feels right_, but its wrong...
``` r
library(targets)
library(gapminder)
library(tidyverse)

tar_script({
  tar_options(packages = c("tidyverse", "gapminder"))
  options(crayon.enabled = FALSE, tidyverse.quiet = TRUE)
  tar_pipeline(
    tar_target(
      gap,
      gapminder %>% group_by(continent) %>% tar_group(),
      iteration = "group",
      format = "fst_tbl"
      ),
    tar_target(
      means,
      mean(gap$lifeExp),
      pattern = map(gap)
      ),
    tar_target(
      combined,
      gap %>% distinct(continent) %>% mutate(means)
    )
    )
  })

tar_make()
#> ● run target gap
#> ● run branch means_5e232b90
#> ● run branch means_51425bc2
#> ● run branch means_faea69ab
#> ● run branch means_03f42e5b
#> ● run branch means_3da8af7a
#> ● run target combined

tar_read(gap)
#> # A tibble: 1,704 x 7
#>    country     continent  year lifeExp      pop gdpPercap tar_group
#>    <fct>       <fct>     <int>   <dbl>    <int>     <dbl>     <int>
#>  1 Afghanistan Asia       1952    28.8  8425333      779.         3
#>  2 Afghanistan Asia       1957    30.3  9240934      821.         3
#>  3 Afghanistan Asia       1962    32.0 10267083      853.         3
#>  4 Afghanistan Asia       1967    34.0 11537966      836.         3
#>  5 Afghanistan Asia       1972    36.1 13079460      740.         3
#>  6 Afghanistan Asia       1977    38.4 14880372      786.         3
#>  7 Afghanistan Asia       1982    39.9 12881816      978.         3
#>  8 Afghanistan Asia       1987    40.8 13867957      852.         3
#>  9 Afghanistan Asia       1992    41.7 16317921      649.         3
#> 10 Afghanistan Asia       1997    41.8 22227415      635.         3
#> # … with 1,694 more rows
tar_read(means)
#> [1] 48.86533 64.65874 60.06490 71.90369 74.32621
tar_read(combined)
#> # A tibble: 5 x 2
#>   continent means
#>   <fct>     <dbl>
#> 1 Asia       48.9
#> 2 Europe     64.7
#> 3 Africa     60.1
#> 4 Americas   71.9
#> 5 Oceania    74.3

gapminder %>% 
  group_by(continent) %>% 
  summarise(mean(lifeExp))
#> `summarise()` ungrouping output (override with `.groups` argument)
#> # A tibble: 5 x 2
#>   continent `mean(lifeExp)`
#>   <fct>               <dbl>
#> 1 Africa               48.9
#> 2 Americas             64.7
#> 3 Asia                 60.1
#> 4 Europe               71.9
#> 5 Oceania              74.3
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattwarkentin** [comment]
I just saw 9c0f334.

> `tar_group` is a vector of consecutive positive integers from 1 to the number of groups. 

Not sure the above is strictly true following from our above conversation. Maybe I'm being too pedantic.

I took a stab a rewording it, not sure if this is more clear or not...

> `tar_group` is a column vector of integers representing group membership. The integers are assigned based on the ordering of levels within `dplyr::group_by()`, and not the order of the rows. The order can be found by running `dplyr::group_keys()` on the grouped data frame.

My last thought - is it too late to rename the added column to `.tar_group` rather than `tar_group`, to take extra precautions to avoid overwriting an existing column of the same name. I know dot-prefixing is very common in the `tidyverse` for this exact reason.
```r
tibble(tar_group = "A") %>% group_by(tar_group) %>% tar_group()
```
```
# A tibble: 1 x 1
# Groups:   tar_group [1]
  tar_group
      <int>
1         1
```

**Comment by wlandau** [comment]
Yup, https://github.com/wlandau/targets/issues/126#issuecomment-663218873 is an issue with ordering. The ordering in `distinct()` is determined by the row order of the dataset.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(gapminder)
  
gapminder %>%
  distinct(continent)
#> # A tibble: 5 x 1
#>   continent
#>   <fct>    
#> 1 Asia     
#> 2 Europe   
#> 3 Africa   
#> 4 Americas 
#> 5 Oceania

gapminder %>%
  arrange(continent) %>%
  distinct(continent)
#> # A tibble: 5 x 1
#>   continent
#>   <fct>    
#> 1 Africa   
#> 2 Americas 
#> 3 Asia     
#> 4 Europe   
#> 5 Oceania
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Sorting on the grouping variable in your original example gives the result we expect.

``` r
library(targets)
library(gapminder)
library(tidyverse)

tar_script({
  tar_options(packages = c("tidyverse", "gapminder"))
  options(crayon.enabled = FALSE, tidyverse.quiet = TRUE)
  tar_pipeline(
    tar_target(
      gap,
      gapminder %>% group_by(continent) %>% tar_group(),
      iteration = "group",
      format = "fst_tbl"
    ),
    tar_target(
      means,
      mean(gap$lifeExp),
      pattern = map(gap)
    ),
    tar_target(
      combined,
      gap %>% distinct(continent) %>% arrange(continent) %>% mutate(means)
    )
  )
})

tar_make()
#> ● run target gap
#> ● run branch means_5e232b90
#> ● run branch means_51425bc2
#> ● run branch means_faea69ab
#> ● run branch means_03f42e5b
#> ● run branch means_3da8af7a
#> ● run target combined

tar_read(combined)
#> # A tibble: 5 x 2
#>   continent means
#>   <fct>     <dbl>
#> 1 Africa     48.9
#> 2 Americas   64.7
#> 3 Asia       60.1
#> 4 Europe     71.9
#> 5 Oceania    74.3
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I find this behavior to be more consistent than basing it on row order. Like you pointed out, we just need to improve the docs.

**Comment by wlandau** [comment]
More examples to show branching order depends on the ordering of the grouping variables:

``` r
library(targets)
library(gapminder)
library(tidyverse)

tar_script({
  tar_options(packages = c("tidyverse", "gapminder"))
  options(crayon.enabled = FALSE, tidyverse.quiet = TRUE)
  tar_pipeline(
    tar_target(
      gap,
      gapminder %>%
        arrange(continent) %>%
        group_by(continent) %>%
        tar_group(),
      iteration = "group",
      format = "fst_tbl"
    ),
    tar_target(
      means,
      tibble::tibble(continent = gap$continent[1], mean(gap$lifeExp)),
      pattern = map(gap)
    )
  )
})

tar_make()
#> ● run target gap
#> ● run branch means_5e232b90
#> ● run branch means_51425bc2
#> ● run branch means_faea69ab
#> ● run branch means_03f42e5b
#> ● run branch means_3da8af7a

tar_read(means)
#> # A tibble: 5 x 2
#>   continent `mean(gap$lifeExp)`
#>   <fct>                   <dbl>
#> 1 Africa                   48.9
#> 2 Americas                 64.7
#> 3 Asia                     60.1
#> 4 Europe                   71.9
#> 5 Oceania                  74.3
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

``` r
library(targets)
library(gapminder)
library(tidyverse)

tar_script({
  tar_options(packages = c("tidyverse", "gapminder"))
  options(crayon.enabled = FALSE, tidyverse.quiet = TRUE)
  
  flip_order <- function(x) {
    x <- as.character(x)
    ordered(x, levels = sort(unique(x), decreasing = TRUE))
  }
  
  tar_pipeline(
    tar_target(
      gap,
      gapminder %>%
        mutate(continent = flip_order(continent)) %>%
        group_by(continent) %>%
        tar_group(),
      iteration = "group",
      format = "fst_tbl"
    ),
    tar_target(
      means,
      tibble::tibble(continent = gap$continent[1], mean(gap$lifeExp)),
      pattern = map(gap)
    )
  )
})

tar_make()
#> ● run target gap
#> ● run branch means_dba3357c
#> ● run branch means_273d0a82
#> ● run branch means_19410a89
#> ● run branch means_ca5e0acc
#> ● run branch means_897077b8

tar_read(means)
#> # A tibble: 5 x 2
#>   continent `mean(gap$lifeExp)`
#>   <ord>                   <dbl>
#> 1 Oceania                  74.3
#> 2 Europe                   71.9
#> 3 Asia                     60.1
#> 4 Americas                 64.7
#> 5 Africa                   48.9
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
> My last thought - is it too late to rename the added column to .tar_group rather than tar_group, to take extra precautions to avoid overwriting an existing column of the same name. I know dot-prefixing is very common in the tidyverse for this exact reason. If it is too late to change, maybe tar_group() should error if that name exists in the data frame already.

It's not too late, but I do have a preference against dotted names, and `tar_group` seems like an uncommon name choice outside `targets`.

**Comment by wlandau** [comment]
Just updated the docs again.
