### ISSUE TITLE
Specify location of cache

### ISSUE THREAD

**Issue by jaredlander** [wlandau/targets#129]
## Prework

* [X] I understand and agree to `targets`' [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [X] I understand and agree to `targets`' [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [X] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

I just learned `{drake}` to the point of being mildly proficient, then I heard about `{targets}` and am excited to try it. At least for my needs, `{drake}`'s ability to specify the location of the cache has been very helpful in numerous ways.

The first situation is that when using a tool like RStudio Connect, we need the cache to be stored somewhere specific, like at '/var/drake-cache/myproject' rather than in the project folder. So I would run code akin to the following.

```
if(using_rsconnect)
{
    cache_path <- '/var/drake-cache/myproject'
} else if
{
    cache_path <- './.drake'
}

if (is.null(drake::drake_cache(cache_path)))
{
    cache <- drake::new_cache(cache_path)
} else
{
    cache <- drake::drake_cache(cache_path)
}
```

The current design choice is [deliberate](https://wlandau.github.io/targets/articles/need.html#better-guardrails-by-design) but I wonder how to solve the RStudio Connect issue within the guardrails.

A second situation is when I have a project with different targets that run at different cadences. For instance, I have a large database table that changes hourly. I have some calculations that run once a day while other calculations run hourly, all based on on an upstream target that reads the table. By setting up different caches, and different plans, I am able to keep those two pipelines separate while in the same project.

I realize I could handle part of this by having multiple targets in a target pipeline with different names that both called the function to read the same table. But I think they would both be triggered (in `{drake}` the target was only triggered based on a database metadata table containing the last time the main table was updated) any time the pipeline is "made" after a table update, when in reality I only want to run one of the targets most of the time and the other target once in a while. This is why I like having different plans with different caches so I can make each plan separately. 

I also realize I could have separate projects for the different cadences, but that doesn't seem ideal either.

After writing this whole explanation I figured out that if I properly name the targets I can use the `names` argument of `tar_make()` and have different jobs call different sets of targets based on the naming pattern. Though I'm going to leave the long-winded writeup in case someone else has the same use case and doesn't think about `names` at first. Plus I also like the idea of multiple pipelines for a given project.

Also, if my explanation of the second situation does not make sense, I'll delete that whole part since it is handled with `names`.

**Comment by wlandau** [comment]
As you pointed out, `targets` is more paternalistic and restrictive in `drake`, which is intentional and it is one of the things that makes `targets` smoother and safer for users. There is less flexibility, but we gain consistency and predictability. 

> The first situation is that when using a tool like RStudio Connect, we need the cache to be stored somewhere specific, like at '/var/drake-cache/myproject' rather than in the project folder. So I would run code akin to the following.

How exactly are you using RStudio Connect? When I use it in pipelines, typically I will have a workflow that renders and R Markdown report or prepares data files for a Shiny app, and then another target that just calls `rsconnect::deployApp()` to deploy the artifacts. This usage does not require the cache to be in a different place.

> A second situation is when I have a project with different targets that run at different cadences. For instance, I have a large database table that changes hourly.

As you pointed out, we can work around this by giving different names to different targets or splitting one project into multiple projects. In general, I would say this sort of think can be resolved with user-side workarounds on a case by case basis.

With `_targets/` always in the same place, small use cases become really easy and super easy, and advanced use cases require extra work. To me, that's a sign that a feature set is well calibrated.

**Comment by jaredlander** [comment]
> How exactly are you using RStudio Connect? When I use it in pipelines, typically I will have a workflow that renders and R Markdown report or prepares data files for a Shiny app, and then another target that just calls rsconnect::deployApp() to deploy the artifacts. This usage does not require the cache to be in a different place.

I am doing the inverse of you. I have the R Markdown document source the plan then call `make()`. This allows me to use the document parameters in the plan. Plus, this means that Connect handles all the scheduling and just naturally publishes the document rather than me calling the API through `{rsconnect}`. This also has the nice benefit of Connect handling all of the package isolation and other nitty gritty details and further allows other contributors to rerender and generally take full advantage of the Connect server. We have seen this setup in a few places now and most of the people we come across prefer for Connect to handle this stuff rather than just publishing to Connect from an outside process.

> As you pointed out, we can work around this by giving different names to different targets or splitting one project into multiple projects. In general, I would say this sort of think can be resolved with user-side workarounds on a case by case basis.

I think this is achievable with some smart naming. That's what I'll do next.

**Comment by brunocarlin** [comment]
I think I solved my problem using

`R.utils::copyDirectory("_targets/objects","data")
`

as a last step on the pipeline, maybe I need to program something like

```
tar_target(
  package_data,
  R.utils::copyDirectory("_targets/objects","data"),
  format = "file"
)
```

**Comment by wlandau** [comment]
Since `R.utils::copyDirectory()` returns the output paths, that's certainly a valid target. But depending on what else is in your pipeline, that may be a lot of data for an R package. Installed R packages are supposed to be less than 5 MB in storage. So you might want to consider selecting a strategic subset of stored targets.

```r
write_data <- function(data, path) {
  saveRDS(data, path)
  path
}

tar_pipeline(
  ..., # previous targets
  tar_target(package_dataset, write_data(some_target, "data/some_target.rds"), format = "file")
)
```

**Comment by brunocarlin** [comment]
Yeah I should probably rely on R packages and Github for the code and let these big dataset objects as artifacts for something like target to keep track and OneDrive to save, good tip
