### ISSUE TITLE
Keep track of package changes in functions

### ISSUE THREAD

**Issue by brunocarlin** [wlandau/targets#132]
## Prework

* [x ] I understand and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x ] I understand and agree to the [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [ x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

So I have this package that is doing data analysis and I define multiple functions that my targets file uses to execute, they are both in the same project, and it works great, this package is awesome! But I would like to make targets be aware if something changed on the package functions so that when I change the analyses functions I don't have to manually invalidate targets

also is it possible to use the functions of the package I am developing without having to re-install and document every time?

**Comment by wlandau** [comment]
Good question. If you put tar_options(envir = getNameapace(“youPackageName”)) in _targets.R, that should work. Just be sure to check tar_visnetwork() to make sure the functions show up. Let me know if that doesn’t work.

**Comment by brunocarlin** [comment]
It looks great thanks!

**Comment by wlandau** [comment]
Glad to hear it.

By the way, in the latest commits to `targets`, `tar_options()` is now `tar_option_set()` and `tar_option()` is now `tar_option_get()`.

**Comment by brunocarlin** [comment]
@wlandau After some time I discovered that while the functions did show up in the workflow and did get invalidated when I updated my package, their calls didn't so the tar_make() functions didn't correctly invalidate my targets

**Comment by wlandau** [comment]
Could you share a reproducible example? I tried to make one, but `targets` seems to be working properly on my end:

``` r
# setup
library(remotes)
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  tar_option_set(envir = getNamespace("biglm"))
  tar_pipeline(
    tar_target(data, data.frame(x = rnorm(100), y = rnorm(100))),
    tar_target(model, biglm(y ~ x, data = data))
  )
})

# Install old biglm.
install_version("biglm", "0.4")
#> Trying https://artifactory.am.lilly.com/artifactory/lrl-cran
#> Downloading package from url: https://artifactory.am.lilly.com/artifactory/lrl-cran/src/contrib/Archive/biglm/biglm_0.4.tar.gz
#> Installing package into '/home/c240390/.R/library'
#> (as 'lib' is unspecified)
tar_make()
#> ● run target data
#> ● run target model
tar_outdated(targets_only = FALSE)
#> character(0)

# Install latest biglm
install_version("biglm", "0.9-2")
#> Downloading package from url: https://artifactory.am.lilly.com/artifactory/lrl-cran/src/contrib/biglm_0.9-2.tar.gz
#> Installing package into '/home/c240390/.R/library'
#> (as 'lib' is unspecified)
tar_outdated(targets_only = FALSE)
#>  [1] ".__NAMESPACE__."      ".__S3MethodsTable__." NA                    
#>  [4] NA                     NA                     "bigglm"              
#>  [7] "bigglm.data.frame"    "bigglm.function"      NA                    
#> [10] "biglm"                NA                     NA                    
#> [13] NA                     NA                     NA                    
#> [16] NA                     NA                     "print.summary.biglm" 
#> [19] "summary.biglm"        "update.biglm"         "update.bigqr"        
#> [22] "vcov.bigglm"          "vcov.biglm"           "model"
tar_make()
#> ✓ skip target data
#> ● run target model
```

<sup>Created on 2020-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
By the way, I recently found out about the [`import`](https://github.com/rticulate/import) package, which is a more flexible alternative to `tar_option_set(envir = getNamespace("biglm"))`: https://stackoverflow.com/questions/63754376/using-the-import-package-with-drake. Also related: https://github.com/ropensci/drake/issues/1286#issuecomment-687647211, https://github.com/ropensci/drake/issues/1286#issuecomment-687765702

**Comment by wlandau** [comment]
Just realized `import` can only fetch functions that are exported from the package. Could be a problem when we have nested functions that change.

> ...while the functions did show up in the workflow and did get invalidated when I updated my package, their calls didn't...

So the function changed but the output is the same? In that case, targets downstream of the initial output do not need to rerun. Example: 

``` r
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  f <- function() 1L
  tarchetypes::tar_plan(
    x = f(),
    y = x,
    z = y
  )
})

tar_make()
#> ● run target x
#> ● run target y
#> ● run target z
tar_visnetwork()
```

![](https://i.imgur.com/FrRw35T.png)

``` r

tar_script({
  options(crayon.enabled = FALSE)
  f <- function() 2L - 1L # changed function but same result
  tarchetypes::tar_plan(
    x = f(),
    y = x,
    z = y
  )
})

tar_visnetwork()
```

![](https://i.imgur.com/YEnhADe.png)

``` r
tar_make()
#> ● run target x
#> ✓ skip target y
#> ✓ skip target z
```

<sup>Created on 2020-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
All those NA's from https://github.com/wlandau/targets/issues/132#issuecomment-689883040 were due to a bug. Should be fixed now. Consequences for this issue thread are the same.

**Comment by wlandau** [comment]
`targets` is designed to avoid tracking packages from functions, so in the static code analysis it ignores namespaced function calls like `biglm::biglm()`.

```{r}
> tar_deps(biglm::biglm(y ~ x, data = data))
[1] "::"   "data" "x"    "y"  
```

This is an unavoidable consequence of the fact that `targets` uses `codetools` as a backend for static code analysis.

```r
> codetools::findGlobals(function() biglm::biglm(y ~ x, data = data))
[1] "::"   "~"    "data"
> codetools::findGlobals(function() biglm(y ~ x, data = data))
[1] "~"     "biglm" "data" 
```

If you visualize the graph, you will see that `biglm()` is not connected to the model target.

```{r}
tar_visnetwork()
```

![Screen Shot 2020-09-10 at 5 19 09 PM](https://user-images.githubusercontent.com/1580860/92808539-d5b99580-f389-11ea-9344-9404692ebb2c.png)

The alternative would be to invent an entirely custom static code analysis system like I did for `drake`, and that made other things difficult to understand and difficult to maintain.

**Comment by wlandau-lilly** [comment]
You may have noticed `tar_deps()` detects `x` and `y` but `codetools::findGlobals()` does not. That's because I made an exception for formulas (#143) because `purrr` lambda functions are so common. I feel like making the same exception for namespaced functions would cause problems for workflows that do not need to track package functions.

**Comment by brunocarlin** [comment]
Very interesting, thanks for the complete explanation, I just switched to calling just functions so no problem

**Comment by psychelzh** [comment]
Maybe this question should be here.

@wlandau What I wondered now is how to let `targets` also track the functions and objects in the global environment after `envir` is already set as the namespace of a package.

The tricky thing here is that I want to add some custom functions to compose the commands of targets, and these functions will definitely not be included into the package. I have found that when set `envir` as the namespace of a package, the objects (functions included) in the global environment are not tracked. Is there a way to let them also been tracked?

**Comment by wlandau** [comment]
See the end of https://github.com/ropensci/drake/issues/1286 for a discussion. The [`import`](https://github.com/rticulate/import) package moves individual functions from one environment to another.

**Comment by psychelzh** [comment]
Thanks. `import` package is doing very well.

**Comment by wlandau** [comment]
Just added new package-tracking functionality with `tar_option_set(imports = your_packages)` (#239, #241). See https://wlandau.github.io/targets-manual/practice.html#packages for details.
