### ISSUE TITLE
Use only a subset of branches using patterns argument (targets equivalent of combine in drake)

### ISSUE THREAD

**Issue by mattwarkentin** [wlandau/targets#134]
## Prework

* [x] I understand and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to the [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

I am wondering what the `{targets}` equivalent is for combining only a subset of the branches. This was previously achieved by using the `combine()` function in `{drake}`. Drawing a blank for how to achieve this in `{targets}`. The code below represents the essence of what I am trying to do, but it doesn't achieve it.

The target `foo` produces 9 branches, and I want the target `bar` to iterate over the sets of three branches that are children of each of the values in the target `abc`. Hopefully that makes sense.

## Reproducible example

``` r
library(targets)

tar_script(
  tar_pipeline(
    tar_target(
      abc,
      LETTERS[1:3]
      ),
    tar_target(
      num,
      1:3
    ),
    tar_target(
      foo,
      paste0(abc, num),
      pattern = cross(abc, num)
    ),
    tar_target(
      bar,
      paste0(foo),
      pattern = map(foo = abc), # seems like I would use combine(...) here
      iteration = "list"
    )
  )
)

tar_make()
#> [34m●[39m run target num
#> [34m●[39m run target abc
#> [34m●[39m run branch foo_5e5455ec
#> [34m●[39m run branch foo_8506c759
#> [34m●[39m run branch foo_9b7031d4
#> [34m●[39m run branch foo_7b9b17fe
#> [34m●[39m run branch foo_cc83bedf
#> [34m●[39m run branch foo_da6d4ad4
#> [34m●[39m run branch foo_8c7bc3b3
#> [34m●[39m run branch foo_e296084a
#> [34m●[39m run branch foo_a71a8961
#> [34m●[39m run branch bar_0607373b
#> [34m●[39m run branch bar_7cc9e85b
#> [34m●[39m run branch bar_941556c1
tar_read(foo)
#> [1] "A1" "A2" "A3" "B1" "B2" "B3" "C1" "C2" "C3"
tar_read(bar)
#> [[1]]
#> [1] "A1" "A2" "A3" "B1" "B2" "B3" "C1" "C2" "C3"
#> 
#> [[2]]
#> [1] "A1" "A2" "A3" "B1" "B2" "B3" "C1" "C2" "C3"
#> 
#> [[3]]
#> [1] "A1" "A2" "A3" "B1" "B2" "B3" "C1" "C2" "C3"

# What I want:
list(
  c("A1", "A2", "A3"),
  c("B1", "B2", "B3"),
  c("C1", "C2", "C3")
)
#> [[1]]
#> [1] "A1" "A2" "A3"
#> 
#> [[2]]
#> [1] "B1" "B2" "B3"
#> 
#> [[3]]
#> [1] "C1" "C2" "C3"
```

<sup>Created on 2020-08-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
All branching in `targets` is dynamic (whereas `combine()` is part of `drake`'s static branching interface) which makes this a little more difficult. But everything gets easier if you use data frames and `tar_group()` with `iteration = "group" (details: https://wlandau.github.io/targets-manual/branching.html#group).

``` r
library(targets)

tar_script({
  options(crayon.enabled = FALSE, tidyverse.quiet = TRUE)
  library(tidyverse)
  tar_pipeline(
    tar_target(num, seq_len(3)),
    tar_target(abc, letters[num]),
    tar_target(
      foo,
      tibble(abc = abc, num = num, value = paste0(abc, num)),
      pattern = cross(abc, num)
    ),
    tar_target(
      foo_grp,
      foo %>%
        group_by(abc) %>%
        tar_group(),
      iteration = "group"
    ),
    tar_target(
      bar,
      foo_grp,
      pattern = map(foo_grp),
      iteration = "list"
    )
  )
})

tar_make()
#> ● run target num
#> ● run target abc
#> ● run branch foo_ff87e85b
#> ● run branch foo_1cf73374
#> ● run branch foo_300ad910
#> ● run branch foo_633abcfe
#> ● run branch foo_5a702919
#> ● run branch foo_5f3e7ce2
#> ● run branch foo_7184d51f
#> ● run branch foo_8fd84bea
#> ● run branch foo_06316692
#> ● run target foo_grp
#> ● run branch bar_e0ea40eb
#> ● run branch bar_743873fc
#> ● run branch bar_0e69c68d

tar_read(bar)
#> [[1]]
#> # A tibble: 3 x 4
#>   abc     num value tar_group
#>   <chr> <int> <chr>     <int>
#> 1 a         1 a1            1
#> 2 a         2 a2            1
#> 3 a         3 a3            1
#> 
#> [[2]]
#> # A tibble: 3 x 4
#>   abc     num value tar_group
#>   <chr> <int> <chr>     <int>
#> 1 b         1 b1            2
#> 2 b         2 b2            2
#> 3 b         3 b3            2
#> 
#> [[3]]
#> # A tibble: 3 x 4
#>   abc     num value tar_group
#>   <chr> <int> <chr>     <int>
#> 1 c         1 c1            3
#> 2 c         2 c2            3
#> 3 c         3 c3            3
```

<sup>Created on 2020-08-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

A couple possible alternatives:

1. Branching (dynamic) with custom filtering on atomic vectors instead of data frames. 
2. Custom metaprogramming to replicate `combine()` from `drake`'s static branching: https://wlandau.github.io/targets-manual/branching.html#metaprogramming

**Comment by mattwarkentin** [comment]
Ah okay. I see what you mean. Thanks for clarifying.

As a side question: When using `tar_group()` and `iteration = "group"`, I'm guess that it will work as long as the column `tar_group` is present, and it is not necessary that the `tibble` keeps the class `grouped_df`, right? This way you can `ungroup()` after `tar_group()` so that the tibble is compatible with group branching, but does not carry the `grouped_df` class which could cause some possible downstream issues.

``` r
library(targets)
library(tidyverse)

mtcars %>% 
  group_by(cyl) %>% 
  tar_group() %>% 
  ungroup()
#> # A tibble: 32 x 12
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb tar_group
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>     <int>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4         2
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4         2
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1         1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1         2
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2         3
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1         2
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4         3
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2         1
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2         1
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4         2
#> # … with 22 more rows
```

<sup>Created on 2020-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
Exactly. The `tar_group` column is all that matters at that point, and attributes left over from `dplyr::group_by()` should be ignored, including the `grouped_df` class if possible. This ensures behavior stays consistent across [specialized storage formats](https://wlandau.github.io/targets/reference/tar_target.html#arguments). For example, `tar_target()` with `format = "fst"` uses the `fst` package to save the data, so it always coerces the stored value to a plain data frame. This process drops the `dplyr` grouping attributes but keeps all the columns, including `tar_group`.

**Comment by wlandau** [comment]
I thought about going further and forcing `tar_group()` to call `dplyr::ungroup()`, but `dplyr` is a heavy dependency, so I do not want `targets` to have to import it.

**Comment by mattwarkentin** [comment]
Thanks for confirming.
