### ISSUE TITLE
targets/callr errors or hangs when trying to import python modules from conda env

### ISSUE THREAD

**Issue by mattwarkentin** [wlandau/targets#135]
## Prework

* [x] I understand and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to the [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

I am trying to build a target which calls an R function which internally uses a python module. When I just interactively run the function it works as expected. When I `tar_make()` the function it errors out (error shown below), and when I `tar_make_clustermq()` it hangs indefinitely until I force terminate the job. 

It very much _seems_ like it's breaking because it cannot load the `python` module that I use within the function. More specifically, it is breaking at the code for loading the module (`alias <- reticulate::import("module")`).

When I call `tar_make()` I get this error:
```
Error in get_result(output = out, options) : 
  callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
Type .Last.error.trace to see where the error occured
```
And here is the traceback:
```
Stack trace:

 1. targets:::tar_make("nlst_nodules")
 2. targets:::callr_outer(targets_function = tar_make_inner, targets ...
 3. targets:::trn(is.null(callr_function), callr_inner(target_script ...
 4. base:::do.call(callr_function, prepare_callr_arguments(callr_fun ...
 5. (function (func, args = list(), libpath = .libPaths(), repos = d ...
 6. callr:::get_result(output = out, options)
 7. throw(new_callr_error(output, killmsg))

 x callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed 
```

I think the code below is a pseudo-reprex, it shows the error, but you probably can't reproduce it exactly the same on your end. I know the module exists in the `r-reticulate` conda envrionment.
``` r
library(targets)

tar_script({
  foo <- function(){
    reticulate::use_condaenv('r-reticulate', conda = '/opt/anaconda3/bin/conda')
    keras <- reticulate::import("keras")
  }
  
  tar_pipeline(
    tar_target(
      t1,
      foo()
    )
  )
})

tar_make()
#> [34m●[39m run target t1
#> Error in get_result(output = out, options): callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
```

<sup>Created on 2020-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Definitely worth noting that this fails too (won't even run the `reprex::reprex()` call:
```r
reprex::reprex({
    reticulate::use_condaenv('r-reticulate', conda = '/opt/anaconda3/bin/conda')
    keras <- reticulate::import("keras")
})
```
```
Rendering reprex...
Error in get_result(output = out, options) : 
  callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
Type .Last.error.trace to see where the error occured
```

**Comment by wlandau** [comment]
Seems like an issue with `callr` + `reticulate` (+ `clustermq`). What happens if you run that `reprex` call just with `callr`? Do you still get the same errors you see with `tar_make()`?

```r
callr::r(function() {
    reticulate::use_condaenv('r-reticulate', conda = '/opt/anaconda3/bin/conda')
    keras <- reticulate::import("keras")
})
```

By the way, do you set anything in your global `.Rprofile` or `.Renviron` files that controls the configuration of Python, Keras, and/or TensorFlow? Because by default, `callr::r()` ignores all your profile files except the ones defined in your working directory. You might have to run `tar_make(callr_arguments = list(system_profile = TRUE, user_profile = TRUE))`.

**Comment by mattwarkentin** [comment]
Yes, definitely seems like a `callr` issue upon more detailed inspection. When I ran the code you provided, I still get the same error as shown previously.

Nothing in my `.Rprofile` or `.Reviron` files should have any influence on using `conda`/`python`/`reticulate`. I am going to file an issue over at `{callr}`. Will report back with any solution.

**Comment by wlandau** [comment]
Sounds good. For what it's worth, I have also been having problems with my Python environments lately.

**Comment by mattwarkentin** [comment]
For posterity...

r-lib/callr#160

**Comment by mattwarkentin** [comment]
See rstudio/reticulate#816 for my solution

**Comment by liutiming** [comment]
I am having this issue with https://github.com/ropensci/targets/discussions/287#discussion-2325836

Double checked that the script runs fine with `targets` alone, but when `clustermq` (and `callr`?) is used, it crashed and burned.

**Comment by wlandau** [comment]
It can be tricky to ensure the remote workers on different compute nodes always have access to the same resources. Some schedules require a special flag to make sure jobs start with the directory you want them to. I use SGE (Grid Engine) so in the template file, I always need to set `-cwd` and call `module load R` on the version of R I am using. (IIRC SLURM automatically sets the job to the main process' working directory, but other schedulers might not.)

```
# This is the cmp.tmpl file I send to the clustermq.template option.
#$ -N {{ job_name }}
#$ -t 1-{{ n_jobs }}
#$ -j y
#$ -cwd # Needed on SGE to make the working directory agree between the workers and the main process.
#$ -V
module load R/4.0.3 # Make sure the R version agrees between the main and worker processes.
CMQ_AUTH={{ auth }} R --no-save --no-restore -e 'clustermq:::worker("{{ master }}")'
```

If that does not work, I recommend reproducing with `clustermq` alone and posting an issue there.
