### ISSUE TITLE
Use spookyhash?

### ISSUE THREAD

**Issue by wlandau** [wlandau/targets#142]
## Prework

* [x] I understand and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to the [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

The spookyhash algorithm itself may or may not be better than the current xxhash64, but the implementation in `digest` is newer and uses `R_xlen_t` instead of `uint32`, which apparently helps avoid collisions. However, switching to `digest`'s spookyhash could also decrease speed and increase the size of `_targets/meta/meta` in storage. Whatever we do, we should decide before the rOpenSci/CRAN submissions in early October. Thoughts? cc @kendonB.

**Comment by wlandau** [comment]
Related: https://github.com/eddelbuettel/digest/issues/97

**Comment by wlandau** [comment]
Hmm... I cannot actually reproduce https://github.com/eddelbuettel/digest/issues/97#issuecomment-485157789 on Mac OS or RHEL 7, and my Windows 10 installation does not have enough memory to test.

**Comment by wlandau** [comment]
And apparently, spookyhash cannot be used with files. The data must be serialized and in memory. `targets` hashes target data files, not in-memory targets, so we cannot use it for the largest and most critical data.

**Comment by wlandau** [comment]
And because we hash files instead of raw vectors, https://github.com/eddelbuettel/digest/issues/97 might not be an issue for `targets` anyway. @kendonB, if you have the chance, would you try https://github.com/eddelbuettel/digest/issues/97#issue-435424785 and but using `digest(algo = "xxhash64", file = TRUE)`? And do we get the same results for [non-iris datasets](https://www.garrickadenbuie.com/blog/lets-move-on-from-iris/)?

Continuing the thread but closing the issue since I no longer think anything can be done in `targets`.

**Comment by kendonB** [comment]
Sorry I missed this earlier. I tried getting this to work with mtcars but couldn't get the basic failure again.
As you ask:
```
digest::digest("big_iris.rds", algo = "xxhash64", file = TRUE) ==
  digest::digest("big_iris2.rds", algo = "xxhash64", file = TRUE)
[1] FALSE
```
digest can detect the changes on my windows machine there on disk. 

However, are you taking care to strip the header information from the objects before saving? The first bytes of an rds object contain file metadata and need to be removed before hashing. digest does this automatically for in-memory objects. A new R version will produce a different hash for the same file on disk.

``` r
digest::digest(mtcars)
#> [1] "a63c70e73b58d0823ab3bcbd3b543d6f"
saveRDS(mtcars, "mtcars.rds")
digest::digest(mtcars) == digest::digest("mtcars.rds", file = TRUE)
#> [1] FALSE
file.remove("mtcars.rds")
#> [1] TRUE
```

<sup>Created on 2020-09-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
>As you ask:
>
> digest::digest("big_iris.rds", algo = "xxhash64", file = TRUE) ==
>  digest::digest("big_iris2.rds", algo = "xxhash64", file = TRUE)
> [1] FALSE
> digest can detect the changes on my windows machine there on disk.

Thanks, this make me think we don't necessarily need to move to spookyhash.

> However, are you taking care to strip the header information from the objects before saving? The first bytes of an rds object contain file metadata and need to be removed before hashing. digest does this automatically for in-memory objects. A new R version will produce a different hash for the same file on disk.

Sounds like this will invalidate RDS targets when the user upgrades R. How would you recommend I remove the metadata? By default, objects are simply saved with `saveRDS()`. And as I said, hashing in `targets` always happens on the file.

https://github.com/wlandau/targets/blob/7c4ae676791a8949c3206ea8d793b1be08dfdaa2/R/class_rds.R#L11-L14

**Comment by kendonB** [comment]
The simplest way to hash would be to read it back into R then run digest on the in-memory object. There does look like skipping that can happen for file hashing so you could try play around with the skip parameter. I'm not sure if the skip number should be for file hashing vs object hashing. This suggests 24 on my machine:

``` r
digest::digest(mtcars)
#> [1] "a63c70e73b58d0823ab3bcbd3b543d6f"
saveRDS(mtcars, "mtcars.rds", compress = FALSE)
out <- sapply(1:100, function(.x){
  digest::digest(mtcars) == digest::digest("mtcars.rds", file = TRUE, skip = .x)
})
which(out)
#> [1] 24
```

<sup>Created on 2020-09-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kendonB** [comment]
I get 23 on ubuntu :/

**Comment by kendonB** [comment]
It's possible that the metadata itself tells you how many to skip to get to the actual object. You could try ask on r-devel

**Comment by wlandau** [comment]
Thanks for giving me an idea of what it would take.

I am not sure I want to hack into data files at such a low level though, even if what we do seems to work now. Maybe we should just use `qs` as the default storage format. `qs` files seem to have the same hashes across R versions and machines where RDS files do not.

On Mac OS with R 4.0.2:

``` r
library(digest)
library(qs)
#> qs v0.23.1. See ChangeLog for update details.
tmp_rds <- tempfile()
tmp_qs <- tempfile()
saveRDS(mtcars, tmp_rds, version = 3L)
qsave(mtcars, tmp_qs)
digest(tmp_rds, file = TRUE, algo = "xxhash64")
#> [1] "a1206da663079206"
digest(tmp_qs, file = TRUE, algo = "xxhash64")
#> [1] "f699d7c81149296f"
```

<sup>Created on 2020-09-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

RHEL 7 with R 3.6.3:

``` r
library(digest)
library(qs)
#> qs v0.23.1. See ChangeLog for update details.
tmp_rds <- tempfile()
tmp_qs <- tempfile()
saveRDS(mtcars, tmp_rds, version = 3L)
qsave(mtcars, tmp_qs)
digest(tmp_rds, file = TRUE, algo = "xxhash64")
#> [1] "dc5c35e11b11b6d0"
digest(tmp_qs, file = TRUE, algo = "xxhash64")
#> [1] "f699d7c81149296f"
```

<sup>Created on 2020-09-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kendonB** [comment]
You will still have to worry about qs (or the underlying compression algo) version changes. rds should almost never change over time. Might be worth asking the qs author.

**Comment by wlandau** [comment]
True. It's still better than guaranteed invalidation with every update to R, but definitely worth touching base.

**Comment by wlandau** [comment]
You know what? In the worst case scenario, hashes will just adopt timestamp-like behavior and the invalidation pattern will resemble Make, which is actually not so bad. What we really need is reasonable assurance that `qread()` will still work on old files.

**Comment by wlandau** [comment]
And of course, there's always `renv`, which most serious reproducible data analysis projects should use anyway.
