### ISSUE TITLE
visnetwork() shows paths with overlap

### ISSUE THREAD

**Issue by MxNl** [wlandau/targets#150]
## Description

I'm using the current github version of targets.
When ploting the interactive network using `visnetwork()` branches of a node that point to a common node are drawn on top of each other:
![grafik](https://user-images.githubusercontent.com/44158557/92380727-f07dd700-f109-11ea-894d-7b3674892a71.png)

## Expected result

Shouldn't it look like this?
![grafik](https://user-images.githubusercontent.com/44158557/92380822-12775980-f10a-11ea-8657-1be7f1315b18.png)

**Comment by wlandau** [comment]
Unfortunately, we cannot control this directly in `targets` because it comes from the automatic behavior of `visNetwork::visHierarchicalLayout()`. I recommend submitting an issue to https://github.com/datastorm-open/visnetwork if it bothers you.

**Comment by MxNl** [comment]
Yes, I thought so! Thanks, I will submit this issue there!
