### ISSUE TITLE
bind_plans alternative?

### ISSUE THREAD

**Issue by kendonB** [wlandau/targets#163]
## Prework

* [x] I understand and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to the [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. **That means posting a runnable, complete, easy to understand [reproducible example](https://www.tidyverse.org/help/) that lets the mainainer fully replicate the issue and see what you see**. Please format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

I'd like to put multiple pipelines together in my `_targets.R`. Can I still do this? If not, is the only targetsy way to define a large project to use functions and either 1) individual targets that do a lot of work or 2) a large number of targets in a single script?

**Comment by kendonB** [comment]
Actually using `c` on target objects seems to work. Is that the right approach?

**Comment by wlandau** [comment]
Yes, either `c()` or `list()` will work. (`list()` is preferable). `tar_pipeline()` can accept an arbitrary number of arbitrarily nested list of target objects.
