### ISSUE TITLE
Bug in tar_render after recent commit

### ISSUE THREAD

**Issue by Robinlovelace** [wlandau/targets#165]
I believe there has been a regression.

After installing the latest version a few minutes ago, my pipeline now fails with the following error message:

```
> # Define targets
> tar_pipeline(
+   tar_target(data, dtc_import(u = "http://data.dft.gov.uk/road-traffic/dft_traffic_counts_raw_counts.zip")),
+   tar_target(summary_dft, summ(data)),
+   tar_target(summary_mode, summary_dft_mode_year(data)),
+   tar_render(readme, "README.Rmd", output_format = "github_document", output_file = "README.md", template = NULL)
+ )
Error in tar_target_raw(name = deparse_language(substitute(name)), command = tar_render_command(path,  : 
  unused argument (template = template)
```

Reproducible example: https://github.com/ITSLeeds/dftTrafficCounts/blob/master/_targets.R

**Comment by wlandau** [comment]
Yup, I was just in the middle of downstream updates after https://github.com/wlandau/targets/issues/161. Upgrading `tarchetypes` to at least https://github.com/wlandau/tarchetypes/commit/6741dcb1bda4c73e90640d1230692b159b744636 should fix this.

**Comment by Robinlovelace** [comment]
Thanks for the explanation and quick fix. Will take a look at your feedback on the package, greatly appreciated!
