### ISSUE TITLE
Ctrl-C doesn't stop clustermq jobs on SLURM

### ISSUE THREAD

**Issue by kendonB** [wlandau/targets#168]
## Prework

* [x] I understand and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to the [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] I am reasonably sure this is a genuine bug in `targets` and most likely not a user error. (If you run into an error and do not know the cause, please submit a "Trouble" issue instead.)
* [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. **That means posting a runnable, complete, easy to understand [reproducible example](https://www.tidyverse.org/help/) that lets the mainainer fully replicate the issue and see what you see**. Please format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

When running tar_make_clustermq interactively then interrupting using Ctrl-C, the slurm jobs keep going. In drake, they do automatically get cancelled.

## Reproducible example

Not able to reproduce but I can send any code you like if it'll help.

## Expected result

The slurm jobs would automatically disappear from the system upon hitting Ctrl-C (or shortly after).

**Comment by wlandau** [comment]
This is the same problem as https://github.com/ropensci/drake/issues/772 because `tar_make()` acts like `r_make()`, not `make()`. The problem is still being worked on in `clustermq` (https://github.com/mschubert/clustermq/issues/150).

**Comment by wlandau** [comment]
Potential workaround: https://github.com/ropensci/drake/issues/772#issuecomment-470964303
