### ISSUE TITLE
Indicate whether the target is being built local or remote in tar_visnetwork()

### ISSUE THREAD

**Issue by mattwarkentin** [wlandau/targets#175]
## Prework

* [ ] I understand and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md) and the [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [ ] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [ ] Please format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

Any interest in somehow indicating which targets are planned to be built locally versus remotely? Maybe it only makes sense show them if they aren't all of an identical type. Could be an option added to `tar_visnetwork()`.

Colours and shapes are already used, so maybe a pattern? Or maybe an image would be good? `visNetwork` supports images and so if you use a PNG with a transparent background, then the existing colours used by `targets` would remain visible. `visNetwork` supports square and circular images, but not diamond (for `cross()`) so I guess thats an issue.

Here is a very hacky and ugly mock-up with the first couple of PNGs I could find with the `targets` colour for `Up to date`

``` r
library(visNetwork)
nodes <- 
  data.frame(
    id = 1:2, 
    shape = rep("image", 2),
    image = c("https://static.thenounproject.com/png/423483-200.png",
              "https://img.icons8.com/cotton/2x/server.png"),
    label = c("Local", "Remote"),
    color = "#0B775E"
)
edges <- data.frame(from = 1, to = 2)

visNetwork(nodes, edges, width = "100%") %>% 
  visNodes(shapeProperties = list(useBorderWithImage = TRUE)) %>%
  visLayout(randomSeed = 2)
```

![](https://i.imgur.com/aA69JfO.png)

---

Side question: Any idea why all of my targets (in my large and complex network) show up in `tar_visnetwork()` as `0 bytes` for their size? When I check the data with `tar_network()` all of the entries are exceptionally small values, for example, one target is listed as `2.848196e-314` bytes when I can see it is taking up 5.4GB of storage on disk in `_targets/objects`. I tried to reproduce but couldn't.

**Comment by wlandau** [comment]
> Side question: Any idea why all of my targets (in my large and complex network) show up in tar_visnetwork() as 0 bytes for their size? When I check the data with tar_network() all of the entries are exceptionally small values, for example, one target is listed as 2.848196e-314 bytes when I can see it is taking up 5.4GB of storage on disk in _targets/objects. I tried to reproduce but couldn't.

This definitely should not happen. If you do figure out how to reproduce it, please let me know. I would also be curious about the `bytes` column in `tar_meta()` since that's where that information is coming from.

**Comment by wlandau** [comment]
I just pulled up a pipeline at my day job where a few of the targets are as large as 1.75 GB, and the plot labels show up fine.

**Comment by wlandau** [comment]
To answer your original question, graphs are a lot of fun to create. We could go any number of directions depending on what we want to communicate. But from a software development perspective, I want core `targets` to do 20% of the work that covers 80% of usage. Anything more complicated than that would quickly produce a heap of technical debt. So I tried to design `targets` anticipating the possibility that someone might want to make a separate R package entirely dedicated to alternative graphs. I believe following functions cover enough to make this possible.

* `tar_network()`: return a list of data frames for vertices and edges
* `tar_manifest()`: return a `drake`-plan-like data frame with any number of input settings you supplied to `tar_target()`, including the `deployment` setting you mentioned. See the `fields` argument for the possible columns.
* `tar_meta()`: return a data frame of output metadata, including hashes, runtimes, sizes, warnings, and errors. Again, see the `fields` argument for the possibilities.

**Comment by mattwarkentin** [comment]
> This definitely should not happen. If you do figure out how to reproduce it, please let me know. I would also be curious about the bytes column in `tar_meta()` since that's where that information is coming from.

Seems to be working as expected now. If it happens again I will try to diagnose further.
