### ISSUE TITLE
Setting up targets package options (writing to global environment)

### ISSUE THREAD

**Issue by asshah4** [wlandau/targets#177]
Hi. I think that the `drake` package is excellent, and really taught me more about functional programming. The `targets` package seems to be fantastic as well, and hope to learn to use it while its being developed. This is my first issue I've filed on github before, so I apologize if its not what's needed.

## Description

In the multiple targets, I'm doing some data cleaning for a particular file using the `dplyr`, which has conflicts with other packages with the `select()` function. I use the `conflicted` package to simplify this issue. However, I'm not sure the order of operations for targets pipeline. I have a function to declare that the `dplyr::select()` is preferred, but its not using this information during run time. 

This is the error shown.

```
Error : [conflicted] `select` found in 2 packages.
Either pick the one you want with `::` 
* MASS::select
* dplyr::select
Or declare a preference with `conflict_prefer()`
* conflict_prefer("select", "MASS")
* conflict_prefer("select", "dplyr") .
Error: callr subprocess failed: [conflicted] `select` found in 2 packages.
Either pick the one you want with `::` 
* MASS::select
* dplyr::select
Or declare a preference with `conflict_prefer()`
* conflict_prefer("select", "MASS")
* conflict_prefer("select", "dplyr") .
```

## Reproducible example

```
library(targets)

problem_function <- function() {
  mtcars %>%
  select(mpg)
}

tar_option_set(packages = c("tidyverse", "conflicted"))
targets <- list(
  tar_target(setup, conflict_prefer("select", "dplyr")),
  tar_target(problem, problem_function())
)

tar_pipleline(targets)
```

## Expected result

I think that the preferred functions should have been used.

## Diagnostic information

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] targets_0.0.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        pillar_1.4.6      compiler_4.0.2    forcats_0.5.0    
 [5] tools_4.0.2       digest_0.6.25     packrat_0.5.0     evaluate_0.14    
 [9] lifecycle_0.2.0   tibble_3.0.3      pkgconfig_2.0.3   rlang_0.4.7      
[13] igraph_1.2.5      cli_2.0.2         rstudioapi_0.11   yaml_2.2.1       
[17] haven_2.3.1       xfun_0.17         withr_2.3.0       dplyr_1.0.2      
[21] knitr_1.30        generics_0.0.2    vctrs_0.3.4       hms_0.5.3        
[25] tidyselect_1.1.0  glue_1.4.2        data.table_1.13.0 R6_2.4.1         
[29] processx_3.4.4    fansi_0.4.1       rmarkdown_2.3     callr_3.4.4      
[33] purrr_0.3.4       magrittr_1.5      codetools_0.2-16  ps_1.3.4         
[37] ellipsis_0.3.1    htmltools_0.5.0   assertthat_0.2.1  utf8_1.1.4       
[41] crayon_1.3.4     
```

**Comment by wlandau** [comment]
With `tar_make()` (not necessarily `tar_make_clustermq()` or `tar_make_future()`, I have not tested them this way) you can actually avoid setting `packages` in `tar_option_set()` and just call `library()` on all your packages before declaring the pipeline.

```{r}
# _targets.R
library(conflicted)
library(targets)
library(tidyverse)
conflict_prefer("select", "dplyr")
problem_function <- function() {
  mtcars %>%
    select(mpg)
}
tar_pipleline(...)
```

However, this can be suboptimal because then your packages will always load even if your targets are up to date, which is a bottleneck. So for maximum performance, I would actually recommend writing your `conflicted` calls in the `.Rprofile` file of the project. 

```{r}
# .Rprofile
conflicted::conflict_prefer("select", "dplyr")
```

Then declare your other packages with `tar_option_set()`.

```{r}
# _targets.R
library(targets)
tar_option_set(packages = "tidyverse")
conflict_prefer("select", "dplyr")
problem_function <- function() {
  mtcars %>%
    select(mpg)
}
tar_pipleline(...)
```

**Comment by joelnitta** [comment]
Is there a reason `conflict_prefer("select", "dplyr")` is still included in `_targets.R` after putting `conflicted::conflict_prefer("select", "dplyr")` in `.Rprofile`?

And a related question: I'm still trying to figure out why `tar_option_set(packages = "tidyverse")` is an improvement over `source("R/packages.R")` as used to be common in drake. Is the idea that you load packages used by all functions with `tar_option_set` and more specific packages that only get used by certain functions with the `packages` argument of `tar_target()`?

**Comment by wlandau** [comment]
> Is there a reason conflict_prefer("select", "dplyr") is still included in _targets.R after putting conflicted::conflict_prefer("select", "dplyr") in .Rprofile?

I meant to discuss `_targets.R` vs `.Rprofile` as two mutually exclusive alternatives. Sorry for the confusion.

> And a related question: I'm still trying to figure out why tar_option_set(packages = "tidyverse") is an improvement over source("R/packages.R") as used to be common in drake. Is the idea that you load packages used by all functions with tar_option_set and more specific packages that only get used by certain functions with the packages argument of tar_target()?

That's one advantage. The other is performance: with `tar_option_set(packages = "tidyverse")`, the package won't load for utility functions like `tar_watch()` and `tar_visnetwork()`, so these functions are quicker to spin up and show graphs. 

To be clear, if you avoid setting the `packages` option, `targets` just looks at whatever packages you loaded in `_targets.R`. In other words, you can still achieve functionality equivalent to what you are used to from `drake`.
