### ISSUE TITLE
tar_make() and _targets.R infinite loop

### ISSUE THREAD

**Issue by asshah4** [wlandau/targets#178]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

This was a very small problem with an easy fix. I included the `tar_make()` function at hte bottom of the **_targets.R** script. I didn't realize this, but it sent my computer to an infinite loop of new R-sessions. I know in the manual it explicitly says:

> Gather the targets in a pipeline with the tar_pipeline() function. tar_pipeline() is flexible: it can accept individual tar_target() objects or nested lists of such objects. Every _targets.R script must end with a tar_pipeline() object, which usually means there is an explicit call to tar_pipeline() at the very bottom.

However, when trying to troubleshoot and go through why the system was crashing, none of the traditional debug issues worked since it went into a spiral of new R sessions running in the background.

## Desired result

I think there should perhaps be a function for those that are new to the `targets` package that just double checks the compliance of the **_targets.R** script before allowing `tar_make()` to run.  Here is an example script, just as a consideration.

```
tar_pipeline_check <- function() {
	file <- file.path(getwd(), "_targets.R")
	script <- scan(file, sep = "\n", what = character())
	pipeline <- tail(script, n = 1)
	truth <- grepl("tar_pipeline", pipeline)
	if(!truth) {
		warning("'_targets.R' does not end with `tar_pipeline(...)`", call. = FALSE)
	}
}
```

I thought it was worth bringing up since it sent my entire system into a tailspin (continually kept starting 100 Mb R-sessions until the entire computer froze). Took me a while to figure it out (but that's likely due to me being a relatively new to R and github).

**Comment by wlandau** [comment]
Good point, I forgot that some users would find this part confusing. And I agree, we want guardrails here. I think https://github.com/wlandau/targets/commit/75124a0a521e790daa75a7bf18ded77a1f102408 has what we need. It scans `_targets.R` for an active call to `tar_make()` or similar function and informatively errors out if detected.
