### ISSUE TITLE
Mixed bag Monday

### ISSUE THREAD

**Issue by mattwarkentin** [wlandau/targets#183]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

### Timestamp to reflect local timezone

I was wondering if it makes sense to try to detect the local timezone, such as with `Sys.timezone()` and use that information to print a local time stamp, rather than `GMT`, and only fall back to `GMT` in cases where a local timezone cannot be determined.
```
✓ 2020-10-05 17:43:20.99 -0400 GMT skip target model_def
✓ 2020-10-05 17:43:21.00 -0400 GMT skip target asir_ns
✓ 2020-10-05 17:43:21.00 -0400 GMT skip target model_formula
```

### Mystery warning

A warning appears when I run `tar_visnetwork()` or `tar_make()` but not `tar_validate()` and I cannot seem to find where the warning originates from. The warning is:
```
Warning messages:
1: <anonymous>: ..1 may be used in an incorrect context
 
2: <anonymous>: ..2 may be used in an incorrect context
 
3: <anonymous>: ..3 may be used in an incorrect context
```
What does `tar_visnetwork()` do that `tar_validate()` doesn't that would elicit this warning? Maybe that would set me on the path to identifying the warning.

**Comment by mattwarkentin** [comment]
Side comment: Both #181 and 1c3890a8d9fb57ecff1a075bc69f9fadb245495b have made huge performance differences for me.

**Comment by mattwarkentin** [comment]
I believe line 62 should be `size`

https://github.com/wlandau/targets/blob/f426c3e863e7a607793122e889f20e6c58353670/vignettes/data.Rmd#L61-L63

**Comment by mattwarkentin** [comment]
This last one maybe deserves its own issue, happy to file separately if you want me to.

I know you have suggested against using this workflow, but I am still interested in using `targets` and `clustermq` so that I can work entirely locally and only run very computationally intensive or time-consuming tasks on the HPC. There are two roadblocks (which are essentially the same underlying issue, access to file systems): 

1) You can't build a target on the HPC that requires access to data stored on the local machine (i.e. any targets with `format = "file"`)

2) The target value is not sent back to the local machine to storage into cache, so the whole pipeline fails

The first issue is relatively easy to solve by only building targets which are any `format` but `"file"`. That way when the dependencies are sent over sockets to the HPC they are pulled from the targets cache and do need access to local files.

The second issue is the major hurdle. After the target gets built on the HPC, no matter if `storage` is set to `"local"` or `"remote"` the data are _attempted_ to be written to cache from the HPC worker or master, and of course it does not have access to the local `_targets/` directory. It seems to me that there needs to be another provision whereby if the `clustermq.scheduler="ssh"`, then the target value is sent back to the spawning R session (the first layer) for saving locally.

**Comment by wlandau** [comment]
> I was wondering if it makes sense to try to detect the local timezone, such as with Sys.timezone() and use that information to print a local time stamp, rather than GMT, and only fall back to GMT in cases where a local timezone cannot be determined.

I actually like GMT because it's predictably compact and some folks might want to write code to process the logs.

**Comment by wlandau** [comment]
> A warning appears when I run tar_visnetwork() or tar_make() but not tar_validate() and I cannot seem to find where the warning originates from.

It helps to run with `callr_function = NULL` and `options(warn = 2) and then call `traceback()`. Otherwise, it's hard to speculate. Could be that `tar_make()` and `tar_visnetwork()` use tidyselect to parse some of the arguments.

**Comment by wlandau** [comment]
> I believe line 62 should be size

fixed

**Comment by mattwarkentin** [comment]
While it's on my mind, do you think that the argument options for `storage/retrieval/deployment` are misnomers? 

- When using `tar_make()` those options don't apply.

- When using `tar_make_clustermq()` and `"multicore"`, everything is happening locally, but `"local"` means master and `"remote"` means worker. 

- When using `tar_make_clustermq()` and `"slurm/sge/whatever"`, everything is happening on the HPC, but `"local"` means master and `"remote"` means worker job. 

- Only when using `tar_make_clustermq()` and `"ssh"` do  `"local"` and `"remote"` actually correspond to the here vs. there meaning. Even in this situation, local and remote carry different meanings for `storage/retrieval` and `deployment`.

**Comment by wlandau** [comment]
> The target value is not sent back to the local machine for storage into cache, so the whole pipeline fails

I am surprised to hear this. When I make the following change [here](https://github.com/wlandau/targets/blob/101b2a3784703d2b376982dceb939ef3fa4cbe91/R/class_rds.R#L22):

```r
store_write_path.tar_rds <- function(store, object, path) {
  print(paste("save", path, "with PID", Sys.getpid()))
  saveRDS(object = object, file = path, version = 3L)
}
```

I can print out the PIDs where the targets run and store the results:

``` r
library(targets)

tar_script({
  options(clustermq.scheduler = "multicore")
  tar_option_set(storage = "local")
  tar_pipeline(
    tar_target(local_deployment, Sys.getpid(), deployment = "local"),
    tar_target(remote_deployment, Sys.getpid(), deployment = "remote")
  )
})

tar_make_clustermq(callr_function = NULL)
#> ● run target local_deployment
#> [1] "save _targets/scratch/local_deployment126374c530470 with PID 75319"
#> ● run target remote_deployment
#> [1] "save _targets/scratch/remote_deployment1264668d2abee with PID 75319"
#> Master: [0.3s 29.1% CPU]; Worker: [avg 14.4% CPU, max 4380372.0 Mb]

Sys.getpid()
#> [1] 75319

tar_read(local_deployment)
#> [1] 75319

tar_read(remote_deployment)
#> [1] 75334
```

<sup>Created on 2020-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So if `storage = "local"`, `targets` really does send the data back to the master process and store it there.

**Comment by wlandau** [comment]
To start troubleshooting your specific error, you can call `tar_make_clustermq(callr_function = NULL)` and print a traceback.

**Comment by wlandau** [comment]
> While it's on my mind, do you think that the argument options for storage/retrieval/deployment are misnomers?

I think you're right on that one. We should change the names while we still have the chance (before the first official release).

**Comment by mattwarkentin** [comment]
Multicore is very different than SSH though, right? Multicore is all happening on my local machine, while for SSH the spawning process is on my local machine, but the master and workers live on the HPC.

**Comment by wlandau** [comment]
Multicore starts different processes with different PIDs, so different PIDs are evidence of different workers (https://github.com/wlandau/targets/issues/183#issuecomment-703955472 is evidence enough). For what it's worth, I repeated that test on an SGE cluster with host names instead of PIDs and I got the same results. Can't share the host names though because they are confidential.

**Comment by mattwarkentin** [comment]
Hmm. I have a couple follow-up questions/comments.

> I repeated that test on an SGE cluster with host names instead of PIDs and I got the same results.

- So your targets files/project lives only on your local computer, but you built the pipeline with `tar_make_clustermq()` and `options(clustermq.scheduler="ssh")` and the data were built on the HPC and passed all the way back to your local machine?

- When using `tar_make_clustermq()` and `options(clustermq.scheduler="ssh")` where does the master process live? On your local computer or the HPC? I assumed the HPC, but then again when I set a target to have `tar_target(deployment = "local")` it builds successfully, so what process did that get built in?

**Comment by mattwarkentin** [comment]
FWIW, we actually first discussed this in https://github.com/ropensci/drake/issues/1295 when I had a much more naive view on how this all worked.

**Comment by wlandau** [comment]
> So your targets files/project lives only on your local computer, but you built the pipeline with tar_make_clustermq() and options(clustermq.scheduler="ssh") and the data were built on the HPC and passed all the way back to your local machine?

Nope, I didn't use SSH. The master process ran on the login node of an SGE cluster. But in the case of `targets`, it's the same situation. `targets` doesn't care what kind of  master or workers you have, it just lets `clustermq` take care of sending the data and work to external processes or different computers.

The only restriction is if the workers do not share the file system of the master process, anything with `format = "file"` is not going to carry over. Dynamic files should only be used in local targets or if the workers have access to the same file system as the master.

> When using tar_make_clustermq() and options(clustermq.scheduler="ssh") where does the master process live? On your local computer or the HPC? I assumed the HPC, but then again when I set a target to have tar_target(deployment = "local") it builds successfully, so what process did that get built in?

For the SSH scheduler, the master process should just be your local machine.

**Comment by mattwarkentin** [comment]
> For the SSH scheduler, the master process should just be your local machine.

Okay, well then what I'm trying to do should work - run select jobs on the HPC but use the master process on my local machine to store and retrieve dependencies. Maybe there is another issue that is breaking the pipeline. I will have to test this out tomorrow when I get to work.

**Comment by mattwarkentin** [comment]
If `storage/retrieval/deployment` are not set to global defaults in `tar_option_set()`, does setting `deployment = "remote"` inside a target have any effect on the behaviour of `storage` or `retrieval`?

**Comment by wlandau** [comment]
All 3 settings act independently. Storage/retrieval still behave differently depending on the setting even if deployment is to the master. But the user only notices the distinction when things run on the workers.

**Comment by mattwarkentin** [comment]
I'm trying to figure out why the example I provided above didn't work. My thought was that because I didn't indicate that storage and retrieval should be "local", that when I set the target to deploy remotely, it tried to store/retrieve on the worker process.

Based on the incomplete code below, will `tbls` be stored using `storage="local"` or `storage="remote"`?
```r
tar_option_set(
  format = "qs",
  packages = pkgs,
  resources = cmq_template
)

tar_pipeline(
  tar_target(
    id,
    1:100,
    deployment = "local"
  ),
  tar_target(
    tbls,
    as_tibble(matrix(runif(100*100), nrow = 100)),
    pattern = map(id),
    deployment = "remote"
  )
)
```

**Comment by wlandau** [comment]
It should use the default "master" (previously "local") storage. `tar_option_set()` sets the defaults for `tar_target()` which you can override with arguments like `storage`. But that should all be moot in your example since `tar_option_get("storage")` is `"master"` if you don't manually set `storage` anywhere.

For you SSH setup, I recommend repeating that same PID test I demo'd in https://github.com/wlandau/targets/issues/183#issuecomment-703955472, only this time use both `Sys.getpid()` and `Sys.info()["nodename"]`. Could eliminate some suspects.

**Comment by mattwarkentin** [comment]
Sounds good. Will test this tomorrow morning. As always, thanks for your patience and help.

**Comment by mattwarkentin** [comment]
> It helps to run with callr_function = NULL and options(warn = 2) and then call traceback(). Otherwise, it's hard to speculate. Could be that tar_make()andtar_visnetwork()` use tidyselect to parse some of the arguments.

```r
options(warn=2)
tar_visnetwork(callr_function = NULL)
```
```
Error: (converted from warning) <anonymous>: ..1 may be used in an incorrect context
```
```r
traceback()
```
```
44: doWithOneRestart(return(expr), restart)
43: withOneRestart(expr, restarts[[1L]])
42: withRestarts({
        .Internal(.signalCondition(simpleWarning(msg, call), msg, 
            call))
        .Internal(.dfltWarn(msg, call))
    }, muffleWarning = function() NULL)
41: .signalSimpleWarning("<anonymous>: ..1 may be used in an incorrect context\n", 
        base::quote(NULL))
40: warning(msg, call. = FALSE)
39: w$warn(paste(paste(w$name, collapse = " : "), ": ", m, loc, "\n", 
        sep = ""))
38: w$signal(paste(v, "may be used in an incorrect context"), w)
37: w$leaf(e, w)
36: walkCode(a, w)
35: collectUsageArgs(e, w)
34: w$call(e, w)
33: walkCode(a, w)
32: collectUsageArgs(e, w)
31: w$call(e, w)
30: walkCode(a, w)
29: collectUsageArgs(e, w)
28: w$call(e, w)
27: walkCode(e[[3]], w)
26: h(e, w)
25: walkCode(e[[i]], w)
24: h(e, w)
23: walkCode(body, w)
22: collectUsageFun(name, formals(fun), body(fun), w)
21: collectUsage(fun, enterGlobal = enter)
20: codetools::findGlobals(fun)
19: deps_function(value)
18: trn(is.function(value), deps_function(value), character(0))
17: FUN(X[[i]], ...)
16: lapply(names, envir_deps, envir = envir, names = names)
15: edges_envir(envir)
14: as.data.frame(d)
13: igraph::graph_from_data_frame(edges)
12: graph_edges(edges_envir(envir))
11: graph_envir(envir)
10: self$update_imports()
9: self$network$update(targets_only = self$targets_only)
8: self$update_network()
7: visual$update()
6: (function (pipeline, targets_only, allow_quosure, exclude_quosure, 
       outdated, label, reporter) 
   {
       pipeline_validate_lite(pipeline)
       allow <- eval_tidyselect(allow_quosure, pipeline_get_names(pipeline))
       exclude <- eval_tidyselect(exclude_quosure, pipeline_get_names(pipeline))
       network <- inspection_init(pipeline, outdated = outdated, 
           reporter = reporter)
       visual <- visual_init(subclass = "visnetwork", network = network, 
           targets_only = targets_only, allow = allow, exclude = exclude, 
           label = label)
       visual$update()
       visual$visnetwork
   })(targets_only = FALSE, allow_quosure = ~NULL, exclude_quosure = ~NULL, 
       outdated = TRUE, label = NULL, reporter = "silent", pipeline = <environment>)
5: do.call(targets_function, targets_arguments)
4: callr_inner(target_script_path(), targets_function, targets_arguments)
3: trn(is.null(callr_function), callr_inner(target_script_path(), 
       targets_function, targets_arguments), do.call(callr_function, 
       prepare_callr_arguments(callr_function, callr_arguments)))
2: callr_outer(targets_function = tar_visnetwork_inner, targets_arguments = targets_arguments, 
       callr_function = callr_function, callr_arguments = callr_arguments)
1: tar_visnetwork(callr_function = NULL)
```

**Comment by wlandau** [comment]
Thanks for the traceback. Looks like an instance of https://github.com/wlandau/targets/issues/164. Unfortunately, the workarounds outside of `codetools` would be super involved.

**Comment by mattwarkentin** [comment]
No worries. It doesn't bother me, I just wasn't sure what the root cause was. I figured it was somehow `purrr`-related since thats really the only time I come across the `..*` syntax. Oh well!

**Comment by mattwarkentin** [comment]
As a side note, `targets` is now a valid topic tag on the RStudio Community Forums (as is `drake`). So users can now tag `targets` when posting issues, which now makes these topics watch-able through preferences. I'm not sure if you have an area in your documentation about the best ways to get help, but you can now consider suggesting people post on the RStudio Community Forums and tag their post with `targets`.

**Comment by wlandau** [comment]
Thanks for letting me know and for helping people with `targets` on RStudio Community. I am watching both tags now (didn't know how at first). Just added some guidance in 8b64f1f4f94f0c713339ba79090c64e6ddc1fbe4 about where to get help.

**Comment by mattwarkentin** [comment]
No problem! I cruise those forums pretty often and this was the first `targets` post I had seen so I asked one of the moderators if they would mind adding `targets` as a topic tag (`drake` was already valid).  I'm watching both of those tags as well so I will try to help where I can.

**Comment by wlandau** [comment]
Changing `"master"` to `"main"`.

**Comment by wlandau** [comment]
Fixed.
