### ISSUE TITLE
Print target runtime in tar_visnetwork

### ISSUE THREAD

**Issue by MxNl** [wlandau/targets#184]
Is it possible to print the runtime of individual targets next to the target label when using tar_visnetwork() like it is printed in `drake` by default?

**Comment by wlandau** [comment]
Yes, it is not the default, but it is possible. And unlike `drake`, you can show the storage size too.

``` r
library(targets)
tar_script({
  tar_pipeline(
    tar_target(x, 1e6),
    tar_target(y, rnorm(n = x))
  )
})
tar_make()
#> [34m●[39m run target x
#> [34m●[39m run target y
tar_visnetwork(label = "time")
```

![](https://i.imgur.com/YAO2lvD.png)

``` r
tar_visnetwork(label = c("time", "size"))
```

![](https://i.imgur.com/B1bIziU.png)

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
`tar_meta()` is another way to get both kinds of information programmatically.

``` r
library(targets)
tar_script({
  tar_pipeline(
    tar_target(x, 1e6),
    tar_target(y, rnorm(n = x))
  )
})
tar_make()
#> [34m●[39m run target x
#> [34m●[39m run target y
tar_meta(names = c("x", "y"), fields = c("seconds", "bytes"))
#> # A tibble: 2 x 3
#>   name  seconds   bytes
#>   <chr>   <dbl>   <int>
#> 1 x       0.002      53
#> 2 y       0.064 7678375
```

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MxNl** [comment]
Thanks for your reply. Stupid me, should have read the documentation more in detail. Sorry for asking.
