### ISSUE TITLE
Add option to specify the output folder and filename in the tar_render command

### ISSUE THREAD

**Issue by robsalasco** [wlandau/targets#188]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

Hi! @wlandau I'm using targets in the creation of pipelines for reports. A feature for me which can be very useful is the possibility to specify the filename and folder of output in the tar_render command.  Would be possible to add it?

Best, Roberto.

**Comment by wlandau** [comment]
I believe this is already possible. You can supply named arguments to `rmarkdown::render()` through `...` in `tar_render()` (e.g. `output_dir`). The target defined by `tar_render()` will include the input path and the return the value of `rmarkdown::render()`, the latter of which is just the vector of paths to the output files generated.

`tar_render()` is actually part of the [`tarchetypes`](https://github.com/wlandau/tarchetypes) package, so if you would post to that issue tracker in the future for similar questions, that would be great.

**Comment by mattwarkentin** [comment]
Hi @robsalasco,

The dots argument (`...`) in `tarchetypes::tar_render()` get passed on to `rmarkdown::render()`, which means you can pass arguments like `output_file` and `output_dir` to `tar_render`.

**Comment by mattwarkentin** [comment]
Beat me to it!

**Comment by wlandau** [comment]
So glad you’re helping me answer questions!  The bandwidth struggle is real.

**Comment by robsalasco** [comment]
thanks for your help @wlandau and @mattwarkentin I forgot the tarchetypes package 😅
