### ISSUE TITLE
reporter = "timestamp" with clustermq produces odd output

### ISSUE THREAD

**Issue by kendonB** [wlandau/targets#197]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [ ] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Once targets get allocated, the main process shows this output:

```
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
Called from: self$wait()
debug: self$crew$send_wait()
debug: Sys.sleep(0.001)
```

## Reproducible example

I presume this is the result of a recent edit - I can try and make something reproducible if the problem is not obvious to you. Here is the top of my main file:
```
library(targets)
options(tidyverse.quiet = TRUE)
tar_option_set(packages = c("tidyverse", 
                            "sf", 
                            "targets",
                            "lubridate",
                            "tidyverse",
                            "ncdf4",
                            "terra",
                            "sf",
                            "progress"))
options(clustermq.scheduler = "slurm", 
        clustermq.template = "slurm_clustermq.tmpl")

tar_option_set(
  resources = list(
    memory = round(12*1024), # MBs
    walltime = 60*10, # minutes
    log_file = "make.log",
    partition = "large"
  )
)
tar_option_set(storage = "worker", retrieval = "worker", memory = "transient",
               error = "continue")
```

## Expected result

These debug messages shouldn't be there. Not 100% but I am trying it right now without the `reporter = "timestamp"` part and no work seems to be getting allocated.

## Diagnostic information
On the latest version.

**Comment by wlandau** [comment]
Sorry about that. Just removed a leftover `browser()` statement, which should fix the issue. The allocation of work is independent of the choice of reporter.
