### ISSUE TITLE
Emit progress indications when run as job in RStudio

### ISSUE THREAD

**Issue by mike-lawrence** [wlandau/targets#202]
## Prework

* [X] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [X] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [X] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

It can be useful to run the make command as a "job" process in RStudio, leaving the main console & process available for other things. This works fine currently (I create a minimal "make.R" then use `rstudioapi::jobRunScript('make.R')`), but it would be nice if, in addition to the output make commands already print, they could also use various functions in the `rstudioapi` to set the state and progress of the build. That is, at the outset use `setJobProgress()` to the total number of targets and use 'jobSetState('running')` to indicate the job has started, use `jobSetStatus()` to indicate what target is being processed and `jobAddProgress()` to update the progress bar, etc.

This is all rather unessential obviously, but I'm willing to work on it and do a PR if I get confirmation here first that it wouldn't be rejected when complete due to concern over possible risk of technical debt.

**Comment by wlandau** [comment]
If this is doable as a superficial addin like [this one](https://github.com/wlandau/targets/blob/main/R/rstudio_addin_tar_visnetwork.R), it sounds worth considering. If `targets` would need to call `setJobProgress()` or `setJobState()` internally during the pipeline, I would prefer not to support it.

`targets` already has equivalent functionality on its own. `tar_make(callr_function = callr::r_bg)` runs the pipeline in the background, and functions `tar_progress()` and `tar_visnetwork()` show runtime progress on a target-by-target basis.

**Comment by wlandau** [comment]
If a superficial addin is possible, please let me know and I will reopen the issue.
