### ISSUE TITLE
tar_make should throw an error if the users asks for a target that doesn't exist

### ISSUE THREAD

**Issue by kendonB** [wlandau/targets#203]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

in `targets-minimal`
```
> tar_make(names = "fut")
✓ Already up to date.
```

**Comment by wlandau** [comment]
Yeah, "already up to date" is a false claim if there are no targets. The current behavior is now to error out if none of the requested targets are found. Any more strict and it would get complicated to process the existing `tidyselect` functionality for `names`.

**Comment by wlandau** [comment]
On reflection, I have decided to revert the error and just avoid the claim that all targets are up to date if no targets were actually selected. I think this leads to a more internally consistent set of behaviors.  

``` r

library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  tar_pipeline()
})

tar_make()

tar_script({
  options(crayon.enabled = FALSE)
  tar_pipeline(tar_target(x, 1))
})

tar_make()
#> ● run target x

tar_make()
#> ✓ skip target x
#> ✓ Already up to date.

tar_make(names = "y")

tar_make(names = c("x", "y"))
#> ✓ skip target x
#> ✓ Already up to date.
```

<sup>Created on 2020-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kendonB** [comment]
Support this solution. Thanks!
