### ISSUE TITLE
splitting a bundle for downstream targets

### ISSUE THREAD

**Issue by yonicd** [wlandau/targets#204]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

How can I split a target bundle to individual bundles to use them downstream in the workflow

```r
library(targets)
library(tarchetypes)

myletters <- letters[1:3]
mypaths <- glue::glue('{myletters}.csv')

purrr::walk(mypaths, file.create)

tar_pipeline(
      tar_files(files, mypaths),
      tar_map(values = tibble::tibble(dat = myletters),
              names = 'dat',
              tar_target(make,identity(files),pattern = map(files))
      )
    )
```

```r
> tar_make()
* run target files_files
v skip branch files_9e70d724
v skip branch files_e83a9ed7
v skip branch files_db2e95b0
* run branch make_a_657916f5
* run branch make_a_f4be25df
* run branch make_a_a28bd2cc
* run branch make_b_657916f5
* run branch make_b_f4be25df
* run branch make_b_a28bd2cc
* run branch make_c_657916f5
* run branch make_c_f4be25df
* run branch make_c_a28bd2cc
```

I am expecting to get back `a.csv` in `make_a` but am getting the concatenated vector from the input.

```r
> tar_read(make_a)
[1] "a.csv" "b.csv" "c.csv"
> tar_read(make_b)
[1] "a.csv" "b.csv" "c.csv"
> tar_read(make_c)
[1] "a.csv" "b.csv" "c.csv"
```

## Reproducible example

* [x] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

**Comment by wlandau** [comment]
Your pipeline uses both static and dynamic branching, and both kinds of branching map over the letters in some way. For each of `make_a` through `make_c`, you have a branch for each of files `a.csv` through `c.csv`. We can use different sets of letters to demonstrate this behavior.

``` r
library(targets)
tar_script({
  options(crayon.enabled = FALSE, tidyverse.quiet = TRUE)
  library(glue)
  library(tarchetypes)
  library(tidyverse)
  letters_dynamic <- letters[c(1L, 2L, 3L)]
  letters_static <- letters[c(24L, 25L, 26L)]
  paths <- glue("{letters_dynamic}.csv")
  walk(paths, file.create)
  tar_pipeline(
    tar_files(files, paths),
    tar_map(
      values = tibble::tibble(letters_static = letters_static),
      names = letters_static,
      tar_target(make, identity(files), pattern = map(files))
    )
  )
})

tar_glimpse()
```

![](https://i.imgur.com/HKUAP0Z.png)

``` r

tar_make()
#> ● run target files_files
#> ● run branch files_75ac31d4
#> ● run branch files_ca8d3386
#> ● run branch files_2835e5ad
#> ● run branch make_x_85bcfde2
#> ● run branch make_x_1bb72e64
#> ● run branch make_x_3e3b41ab
#> ● run branch make_y_85bcfde2
#> ● run branch make_y_1bb72e64
#> ● run branch make_y_3e3b41ab
#> ● run branch make_z_85bcfde2
#> ● run branch make_z_1bb72e64
#> ● run branch make_z_3e3b41ab

tar_read(make_x)
#> [1] "a.csv" "b.csv" "c.csv"
```

<sup>Created on 2020-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

To carry the computation forward, I recommend adding downstream targets within `tar_map()` that depend on `make`. You can use the same branching strategy: below, the branches of `downstream_x` directly correspond to the branches of `make_x`.

``` r
library(targets)
tar_script({
  options(crayon.enabled = FALSE, tidyverse.quiet = TRUE)
  library(glue)
  library(tarchetypes)
  library(tidyverse)
  letters_dynamic <- letters[c(1L, 2L, 3L)]
  letters_static <- letters[c(24L, 25L, 26L)]
  paths <- glue("{letters_dynamic}.csv")
  walk(paths, file.create)
  tar_pipeline(
    tar_files(files, paths),
    tar_map(
      values = tibble::tibble(letters_static = letters_static),
      names = letters_static,
      tar_target(make, identity(files), pattern = map(files)),
      tar_target(downstream, paste0("downstream_", make), pattern = map(make)) # downstream targets
    )
  )
})

tar_glimpse()
```

![](https://i.imgur.com/uBuAb63.png)

``` r

tar_make()
#> ● run target files_files
#> ● run branch files_75ac31d4
#> ● run branch files_ca8d3386
#> ● run branch files_2835e5ad
#> ● run branch make_x_85bcfde2
#> ● run branch make_x_1bb72e64
#> ● run branch make_x_3e3b41ab
#> ● run branch make_y_85bcfde2
#> ● run branch make_y_1bb72e64
#> ● run branch make_y_3e3b41ab
#> ● run branch make_z_85bcfde2
#> ● run branch make_z_1bb72e64
#> ● run branch make_z_3e3b41ab
#> ● run branch downstream_x_9dc0ea3c
#> ● run branch downstream_x_dcb160bf
#> ● run branch downstream_x_fda455e3
#> ● run branch downstream_y_57f9bafb
#> ● run branch downstream_y_e8130633
#> ● run branch downstream_y_9aa7920d
#> ● run branch downstream_z_a30940dd
#> ● run branch downstream_z_68f74cbf
#> ● run branch downstream_z_b1feac46

tar_read(make_x)
#> [1] "a.csv" "b.csv" "c.csv"

tar_read(downstream_x)
#> [1] "downstream_a.csv" "downstream_b.csv" "downstream_c.csv"
```

<sup>Created on 2020-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yonicd** [comment]
sorry my question isnt clear.

If i have 3 data.frame then make_x will merge them. I want to have make_x be only the the x data.frame, make_y the second data.frame and make_z the third data.frame.

**Comment by yonicd** [comment]
my real work flow is the following
![2020-10-28 12_25_02-217-MDD-303 - adcm - RStudio](https://user-images.githubusercontent.com/1755487/97465682-ac909c80-1918-11eb-8258-ef94129b0e5a.png)

where i want to use tar_map up to reading in the data but then i need to use the data in different ways in the preprocessing (thus splitting up) before the reports.

What would be a better way to set up the workflow?

**Comment by wlandau** [comment]
`make_x` only gets merged if you refer to the entire thing at once (i.e. without `pattern = map(...)` or with `tar_read(make_x)`). With `tar_read(make_x, branches = 2)` or `tar_target(downstream, paste0("downstream_", make), pattern = map(make))`, you get individual branches. The former should be fine for reports. Otherwise, you could create downstream targets that filter out just what you need:

``` r

library(targets)
tar_script({
  options(crayon.enabled = FALSE, tidyverse.quiet = TRUE)
  library(glue)
  library(tarchetypes)
  library(tidyverse)
  letters_dynamic <- letters[c(1L, 2L, 3L)]
  letters_static <- letters[c(24L, 25L, 26L)]
  paths <- glue("{letters_dynamic}.csv")
  walk(paths, file.create)
  tar_pipeline(
    tar_files(files, paths),
    tar_map(
      values = tibble::tibble(letters_static = letters_static),
      names = letters_static,
      tar_target(make, identity(files), pattern = map(files)),
      tar_target(downstream, unname(grep("^a", make, value = TRUE)))
    )
  )
})

tar_make()
#> ● run target files_files
#> ● run branch files_75ac31d4
#> ● run branch files_ca8d3386
#> ● run branch files_2835e5ad
#> ● run branch make_x_85bcfde2
#> ● run branch make_x_1bb72e64
#> ● run branch make_x_3e3b41ab
#> ● run branch make_y_85bcfde2
#> ● run branch make_y_1bb72e64
#> ● run branch make_y_3e3b41ab
#> ● run branch make_z_85bcfde2
#> ● run branch make_z_1bb72e64
#> ● run branch make_z_3e3b41ab
#> ● run target downstream_x
#> ● run target downstream_y
#> ● run target downstream_z

tar_read(downstream_x)
#> [1] "a.csv"
```

<sup>Created on 2020-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yonicd** [comment]
got it. thanks!

**Comment by yonicd** [comment]
Apologies, but i am still confused on how to select data.frames. 

The example you gave above is to grep a character vector. In the use case I have I need to map each data.frame in the make list to a new target downstream_{x,y,z}

**Comment by wlandau** [comment]
The principle is the same, but you would do something like `dplyr::filter(make, id == "a")` instead of `grep("^a", make, value = TRUE)`. This requires that you create a new column like `id` to distinguish among the branches.

**Comment by yonicd** [comment]
in such a case downstream_{y,z} would have id=='a' though, right?

**Comment by wlandau** [comment]
True. So you would need something like `tar_target(downstream, dplyr::filter(make, file_name = path), pattern = map(make, path))`.

**Comment by yonicd** [comment]
that still picks up all the letters since it is looping over the elements and that value is there regardless. what you are suggesting would work in a post merge object.

**Comment by wlandau** [comment]
Inside the pipeline itself, this is the only way to promote a branch to a full unbranched target (a "stem"). The only workaround I can think of is complete reliance on static branching.

**Comment by yonicd** [comment]
ok. thanks. 

i think it may be useful to have a counterpart to `tar_combine`; `tar_split` or `tar_flatten` that uses the same idea as `tar_map` but promotes the branches up one level based on a data_frame or list to map it to the stem.

**Comment by wlandau** [comment]
This is not possible in the general case, unfortunately. In dynamic branching, you don't need to know how many branches there will be in advance, or what there names should be. With static branching, every single target needs to be declared in advance. So `tar_split()` would not be able to tell how many splits to create.
