### ISSUE TITLE
Installation instructions getting 404

### ISSUE THREAD

**Issue by dncnbrn** [wlandau/targets#206]
If I follow the installation instructions I get:

```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`wlandau`) and repo name (`targets`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

I get this from both a Mac and a Windows machine, and I'm able to install other GitHub packages at the same time.

**Comment by ginolhac** [comment]
branch was renamed to `main`. You need to use `remotes::install_github("wlandau/targets@main")`

**Comment by wlandau** [comment]
`install_github("wlandau/targets")` does work with `remotes` version 2.2.0 (current CRAN)` (https://github.com/r-lib/remotes/pull/510). Please update your installation of `remotes`.
