### ISSUE TITLE
Torch serialization not working properly; pointer issues.

### ISSUE THREAD

**Issue by mattwarkentin** [wlandau/targets#209]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Hi @wlandau,

It seems like something about the `torch` serialization isn't working right. Or maybe I'm not quite understanding how the serialization/unserialization works. I thought the serialization/unserialization meant you could pass objects in memory from main to worker.

But here is a reprex that I think showcases the issue. The `torch` object has to be retrieved by the worker, or else the external pointer is invalid.

Mostly this wouldn't be an issue, but this means `torch` objects cannot be loaded on the `"main"` process and passed to the HPC via `ssh` (and maybe this affects AWS storage/retrieval too, but I don't use it so I can't test it out).

### `tar_make_clustermq()` with `"main"` retrieval

``` r
library(targets)

tar_script({
  library(targets)
  library(torch)
  
  options(clustermq.scheduler = "multiprocess")
  
  tar_option_set(
    packages = c("torch"), 
    retrieval = "main"
    )
  
  tar_pipeline(
    tar_target(
      tensor, 
      torch_zeros(10), 
      format = "torch"
      ),
    tar_target(
      test, 
      as.array(tensor)
      )
  )
})

tar_make_clustermq()
#> [34m●[39m run target tensor
#> [34m●[39m run target test
#> [31mx[39m error target test
#> Warning in self$crew$finalize() : Unclean shutdown for PIDs: 24760
#> Error : external pointer is not valid .
#> Error: callr subprocess failed: external pointer is not valid .
tar_read(tensor)
#> torch_tensor
#>  0
#>  0
#>  0
#>  0
#>  0
#>  0
#>  0
#>  0
#>  0
#>  0
#> [ CPUFloatType{10} ]
tar_read(test)
#> Error in gzfile(file, "rb"): invalid 'description' argument
```

### `tar_make_clustermq()` with `"worker"` retrieval
``` r
library(targets)

tar_script({
  library(targets)
  library(torch)
  
  options(clustermq.scheduler = "multiprocess")
  
  tar_option_set(
    packages = c("torch"), 
    retrieval = "worker"
    )
  
  tar_pipeline(
    tar_target(
      tensor, 
      torch_zeros(10), 
      format = "torch"
      ),
    tar_target(
      test, 
      as.array(tensor)
      )
  )
})

tar_make_clustermq()
#> [34m●[39m run target tensor
#> [34m●[39m run target test
#> Master: [1.3s 4.6% CPU]; Worker: [avg 74.2% CPU, max 3329675.0 Mb]
tar_read(tensor)
#> torch_tensor
#>  0
#>  0
#>  0
#>  0
#>  0
#>  0
#>  0
#>  0
#>  0
#>  0
#> [ CPUFloatType{10} ]
tar_read(test)
#>  [1] 0 0 0 0 0 0 0 0 0 0
```

**Comment by mattwarkentin** [comment]
If an object is loaded on the main process, is it serialized again before it is passed to the work?

**Comment by wlandau** [comment]
You're right, and this is going to take some careful work to address.

**Comment by wlandau** [comment]
Started in branch `209`. Implementation notes:

* [x] Serialize at the object level, not the value level.
* [x] Make shallow copies of the targets for the subpipeline.
* [ ] Remove stashing and restoring.
* [ ] Reinitialize the value instance of each subpipeline target if `retrieval` is `"worker"`.
* [ ] Create subpipeline if and only if `deployment` is `"worker"`, not `retrieval`.
* [ ] In `tar_make()`, set `deployment` to `"main"` for all targets.

**Comment by wlandau** [comment]
Working through this issue not only solved the original problem, but also led to some nice internal infrastructure improvements. Thanks @mattwarkentin for speaking up and for the nice reprex.

**Comment by mattwarkentin** [comment]
That's great! I'm glad to hear that this issue led to something deeper than just squashing a bug.

**Comment by mattwarkentin** [comment]
Happy to report this all works for `ssh` deployment too. I was a little concerned because `clustermq` has its own master process separate from the `targets` master process when using `ssh`. But it works great!

**Comment by wlandau** [comment]
Awesome!
