### ISSUE TITLE
New dynamic branching patterns

### ISSUE THREAD

**Issue by wlandau** [wlandau/targets#215]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

The infrastructure from #212 gives us the ability to easily create more dynamic branching patterns. I am thinking of new map-like patterns for unequal-length objects. 

Along with this issue, we should probably formalize [`pattern_functions`](https://github.com/wlandau/targets/blob/b6c338e77f85177dbcebc52261bc986ea6574231/R/class_pattern.R#L330-L350) into a formal instance of a formal R6 class (called "tar_dynamic").

**Comment by mattwarkentin** [comment]
> I am thinking of new map-like patterns for unequal-length objects.

Maybe I am drawing a blank but what is the use-case for this?

**Comment by wlandau** [comment]
I just remember encountering use cases where I need to map over targets `x` and `y`, where `y` actually corresponds to `rep(x, each = 3)`. On reflection, this idea does not seem very well formed yet and we need to see how use cases play out before brainstorming. I'm not actually sure we actually need any alternative patterns.

But for the future, we should definitely be open-minded for new patterns that might be useful. I have coded things so adding a new pattern is trivially easy. It's just a new method in the [class that stores dynamic methods](https://github.com/wlandau/targets/blob/main/R/class_dynamic.R), plus a [user-side helper](https://github.com/wlandau/targets/blob/main/R/tar_dynamic_map.R) to let people explore patterns outside the pipeline.





I don't really have any
