### ISSUE TITLE
Add options to limit object sizes

### ISSUE THREAD

**Issue by yogevherz** [wlandau/targets#223]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

First of all, this is an amazing package. I've been using it for a while and I very much enjoy it. 

I would like to suggest adding an option to limit the size of each object saved in the `_targets/obects` cache. Something of the sort of `tar_options(max_object_size = "1kb")`.

The reasoning behind this is as follows: When someone in our organisation pushes a code to github which was written using the `targets` package, they also push to the repository the contents of `_targets` folder. This is desired, because it allows me or any other use to run the pipeline as if it was run on my computer and access any intermediate results without having to compute them again. However, we do not want large files such as datasets of intermediate results in our repository, we would like users to upload them to AWS and read them in the appropriate place (which can be done very easily with `targets`). If `targets` could enforce this by not allowing large objects to be saved it would make our lives much easier. 
What do you think? Perhaps we doing this wrong and there is a better way to collaborate on the same project?

**Comment by wlandau** [comment]
Glad you like `targets`, and it's great to hear the AWS storage integration is turning out to be useful.

In your case, I recommend defining a Git pre-commit hook with a low hard limit for the size of an individual file ([example here](https://stackoverflow.com/questions/39576257/how-to-limit-file-size-on-commit)). `usethis::use_hook("pre-commit", ...)` makes the process more convenient. I think `targets` should stay separate from all this.
