### ISSUE TITLE
How to set a custom trigger just as `drake` does

### ISSUE THREAD

**Issue by psychelzh** [wlandau/targets#227]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

Just as the title goes, I want to define a custom trigger (e.g., when some specific value changes) to trigger a target rerun. What I have learnt is to set `cue` with `tar_cue`, which unfortunately does not have such custom trigger. Is there a way to do that in `targets`?

**Comment by wlandau** [comment]
[`tarchetypes`](https://github.com/wlandau/tarchetypes) has helpers for this. I recommend having a look at [`tar_change()`](https://wlandau.github.io/tarchetypes/reference/tar_change.html), [`tar_force()`](https://wlandau.github.io/tarchetypes/reference/tar_force.html), and [`tar_skip()`](https://wlandau.github.io/tarchetypes/reference/tar_skip.html).

**Comment by wlandau** [comment]
`tar_change()` probably suits your use case best.

**Comment by psychelzh** [comment]
Thanks for you quick respond. `tar_change()` is very promising. However, its behavior is actually different from `drake`, because it adds a target which is always rerun. In this way, all the targets depending on it will be shown as outdated, making the dependency network visualization very misleading.

**Comment by wlandau** [comment]
This implementation strategy was necessary for a maintainable implementation. Arbitrarily flexible triggers in `drake` were seldom useful but a huge burden on the infrastructure. I still believe the current behavior makes the right tradeoffs.

**Comment by psychelzh** [comment]
Thanks, this makes me rethink about my workflow and the usage of this package. I am learning these now, and your opinion is insightful.
