### ISSUE TITLE
Suggestion: `tar_progress()` should inform errors of package loading

### ISSUE THREAD

**Issue by psychelzh** [wlandau/targets#228]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Currently, when package loading errored, the `tar_progress()` always reports that the first target is been running, which is misleading.

**Comment by wlandau** [comment]
Thanks, should be fixed in ff1e3e3ef4a67346b55bef441b777167bd8fd536.
