### ISSUE TITLE
is there a way to save visnetwork as a figure without access to the browser

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#233]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Question
For users without browser access (working on a computer cluster for example), is there a way to save visnetwork as a figure? Currently only able to use `tar_network` because `tar_visnetwork` returns the following:

```
Error in viewer(index_html) : 
  'browser' must be a non-empty character string
```

## Reproducible example

Running `tar_visnetwork()` in the default _targets.R generated by `tar_script()`

**Comment by ginolhac** [comment]
Hi,
I am using this from Noam Ross, works well
```r
visNetwork::visSave(targets::tar_visnetwork(),
                    here::here("artifacts", "targets_graph.html"))
```

**Comment by liutiming** [comment]
@ginolhac thank you so much! for some reason `here` did not work for me, so I just saved the html. :)

**Comment by wlandau** [comment]
Thanks, @ginolhac. `visSave()` is definitely the way to go. And`webshot` should help with static images.

```r
library(targets)
library(visNetwork)
library(webshot)
widget <- tar_visnetwork()
visSave(widget, "graph.html")
webshot("graph.html", file = "graph.png")
```
