### ISSUE TITLE
What is the best way to make sure dynamic branch reruns based on package functions

### ISSUE THREAD

**Issue by psychelzh** [wlandau/targets#235]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

I have write a package with many functions to do analysis. They are a little time-consuming, so I want to use dynamic branch to make sure the pipeline only reruns specific target only its corresponding function is modified.

## Reproducible example

All files required are attached here: [test-targets-branching.zip](https://github.com/wlandau/targets/files/5606722/test-targets-branching.zip)

Here is my `_targets.R` file:

```r
library(tidyverse)
library(targets)
library(tarchetypes)
tar_option_set(packages = "tidyverse")
tar_pipeline(
  tar_target(
    file,
    "test.csv",
    format = "file"
  ),
  tar_target(
    file_content,
    read_csv(file)
  ),
  tar_target(
    config,
    read_csv("config.csv") %>%
      # functions are from package `dataproc.iquizoo`, use this is to make sure
      # "fun" is changed when the function is changed.
      mutate(fun = map(fun, ~getFromNamespace(.x, "dataproc.iquizoo"))) %>%
      group_by(fun) %>%
      tar_group(),
    iteration = "group",
    cue = tar_cue(mode = "always")
  ),
  tar_target(
    result,
    file_content %>%
      inner_join(config, by = "y") %>%
      mutate(z = map(fun, ~ .x(data.frame()))),
    pattern = map(config)
  )
)
```

Two sample files used:

`config.csv`:

```
y,fun
2,multisense
3,crt
4,multisense
5,crt
```

`test.scv`:

```
x,y
1,2
1,2
3,4
1,2
4,5
2,5
```

This script needs `tidyverse` package.

### Older version of package

Make targets under version `0.2.2` of my package:

```r
remotes::install_github("psychelzh/dataproc.iquizoo@0.2.2")
targets::tar_make()
```

The making results will be:

```r
-- Attaching packages --------------------------------------- tidyverse 1.3.0 --
√ ggplot2 3.3.2     √ purrr   0.3.4
√ tibble  3.0.4     √ dplyr   1.0.2
√ tidyr   1.1.2     √ stringr 1.4.0
√ readr   1.4.0     √ forcats 0.5.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
* run target file
* run target config
|
-- Column specification --------------------------------------------------------
cols(
  y = col_double(),
  fun = col_character()
)

* run target file_content
-
-- Column specification --------------------------------------------------------
cols(
  x = col_double(),
  y = col_double()
)

* run branch result_45bd6462
* run branch result_06865d18
-here were 13 warnings (use warnings() to see them)
```

### Newer version of package

I fixed some bug in `0.2.3` version of function `multisense()` only (see [change log](https://github.com/psychelzh/dataproc.iquizoo/compare/0.2.2...0.2.3)), so I expect that only one branch will be rerun (corresponding to "multisense" in `config.csv`), but it reruns all branches:

```r
remotes::install_github("psychelzh/dataproc.iquizoo@0.2.3")
targets::tar_make()
```

Making processes are as follows:

```r
-- Attaching packages --------------------------------------- tidyverse 1.3.0 --
√ ggplot2 3.3.2     √ purrr   0.3.4
√ tibble  3.0.4     √ dplyr   1.0.2
√ tidyr   1.1.2     √ stringr 1.4.0
√ readr   1.4.0     √ forcats 0.5.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
√ skip target file
* run target config
|
-- Column specification --------------------------------------------------------
cols(
  y = col_double(),
  fun = col_character()
)

√ skip target file_content
* run branch result_e92a1aed
* run branch result_ecd561a7
/here were 13 warnings (use warnings() to see them)
```

See those two branches both rerun, which is not desirable.

## Further thoughts

I have tried with functions in global environment. This method works! I guess that there might be something special for `namespace`? Is there a way?

After some more tests, I am guessing that the `bytecode` might be the reason. So the problem here might be how to remove those `bytecode` binding with the object returned by `get()` or `getFromNamespace()`.

Although `bytecode` is a nuisance information which `identical()` ignore when comparing two functions directly, but when it is nested in a `data.frame`, it becomes meaningful in comparing rows of data.

**Comment by psychelzh** [comment]
I further tried to add fun to a target as follows:

`_targets.R` (it contains examples using functions in global environment):

```r
library(tidyverse)
library(targets)
library(tarchetypes)
tar_option_set(packages = "tidyverse")
test1 <- function() { 1 }
test2 <- function() { 3 }
tar_pipeline(
  tar_target(
    file,
    "test.csv",
    format = "file"
  ),
  tar_target(
    file_content,
    read_csv(file)
  ),
  tar_target(
    config,
    read_csv("config.csv") %>%
      mutate(fun = map(fun, ~ getFromNamespace(.x, "dataproc.iquizoo"))) %>%
      group_nest(fun, .key = "match"),
    cue = tar_cue(mode = "always")
  ),
  tar_target(
    funs,
    pull(config, "fun"),
    iteration = "list"
  ),
  tar_target(
    matches,
    pull(config, "match"),
    iteration = "list"
  ),
  tar_target(
    result,
    file_content %>%
      inner_join(matches, by = "y") %>%
      mutate(z = funs(data.frame())),
    pattern = map(funs, matches)
  ),
  tar_target(
    config_global,
    read_csv("config_global.csv") %>%
      mutate(fun = map(fun, get)) %>%
      group_by(fun) %>%
      tar_group(),
    iteration = "group",
    cue = tar_cue(mode = "always")
  ),
  tar_target(
    result_global,
    file_content %>%
      inner_join(config_global, by = "y") %>%
      mutate(z = map(fun, ~ .x())),
    pattern = map(config_global)
  )
)
```

In two versions of `funs` target, `funs[2]` is identical (`identical()` says so), but all branches rerun.

**Comment by wlandau** [comment]
`targets` is designed to think about functions as preexisting objects in the global environment as opposed to return values produced by targets. If your functions are part of a package, my usual recommendation is to manually set the pipeline's environment to the package's environment instead of global.

```r
# In _targets.R:
tar_option_set(envir = getNamespace("dataproc.iquizoo"))
```

Then, call those functions normally (with symbols) so `targets` can detect dependency relationships using static code analysis (check with `tar_visnetwork()`).

```r
tar_pipeline(
  tar_target(a, multisense()),
  tar_target(b, crt())
)
```

You can even statically branch over the names of functions with `tar_map()` from `tarchetypes`. (Check the results with `tar_visnetwork()`).


```r
tar_pipeline(
  tar_map(
    list(fun = rlang::syms(c("multisense", "crt"))),
    tar_target(x, fun(arg))
  )
)
```

But *dynamic* branching over functions returned from a target is not really something `targets` will ever do well. So at this point, I would like to take a step back and ask what the purpose of the pipeline is. I feel like users should not have to do that and cleaner workarounds are possible.

**Comment by psychelzh** [comment]
Thanks for your great advice. I am sorry that I even did not know the `envir` option. I will try that option.

The reason for dynamic branching over functions is just because I want all the branching targets automatically combined (static branching results are not needed at this point). But after some trials and rethink about that, I have to admit that I should have used a static branch when dealing with **functions**.

In addition, is there a better way to easily select static target names to combine? For example supporting `tidy-select`?

**Comment by wlandau** [comment]
Yeah, static branching requires an explicit `tar_combine()`

**Comment by wlandau** [comment]
But you can work with the actual `target` objects to select the specific ones you want to combine.

``` r
library(targets)
tar_script({
  library(tarchetypes)
  mapped <- tar_map(
    values = list(fun = rlang::syms(c("multisense", "crt"))),
    unlist = TRUE,
    tar_target(a, fun(arg1)),
    tar_target(b, fun(arg2))
  )
  combined <- tar_combine(
    combined,
    mapped$a_crt,
    mapped$b_multisense
  )
  tar_pipeline(mapped, combined)
})
tar_visnetwork(targets_only = TRUE)
```

![](https://i.imgur.com/DExPtk2.png)

<sup>Created on 2020-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by psychelzh** [comment]
@wlandau I have mostly completed the refactoring to a static branch. What I wondered now is how to let `targets` also track the functions and objects in global environment after `envir` is already set as the namespace of a package.

The tricky thing here is I want to add some custom functions to compose my commands of targets, and these functions will definitely not be included into the package. I have found that when set `envir` as the namespace of a package, the objects (functions included) in the global environment are not tracked.

**Comment by wlandau** [comment]
See https://wlandau.github.io/targets-manual/practice.html#packages for the new package-tracking functionality with `tar_option_set(imports = your_packages)`.

**Comment by psychelzh** [comment]
@wlandau There is a typo in the manual (it should be "targets" rather than "drake"):

![image](https://user-images.githubusercontent.com/13306020/100837558-d440ca80-34ab-11eb-9311-6cf730935acb.png)

**Comment by psychelzh** [comment]
BTW, does this option support import from R script?
