### ISSUE TITLE
Debugging reruns every targets when not in a fresh R session

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#238]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Question

The user manual recommends starting debugging session in a fresh R session. I tried what would happen if I do not run in a fresh R session so the second time I called `targets::tar_make_clustermq(workers = 16, callr_function = NULL)` all targets are run. Is this the expected behavior?

**Comment by wlandau** [comment]
That's exactly what I was warning about. If you set `callr_function` to `NULL`, then the detritus in your global environment gets mixed up with the global objects and functions you define in `_targets.R`, which could definitely invalidate some of your targets. To check before running things, you can run `tar_visnetwork(callr_function = NULL)`.
