### ISSUE TITLE
Bind/combine two branched target without loading them in RAM

### ISSUE THREAD

**Issue by glep** [wlandau/targets#242]
Hi @wlandau ,

I struggle with a RAM problem.
Let's say that I have the following plan.

I have two sets of input lists. I want to run my `run_model()` function on each parameters list.
I could create two targets with this function mapped on `model_input` and `other_model_input`, but for clarity purpose, I would rather combine the `run_model()` calls.

The following code does what I want.

``` r
tar_option_set(
  iteration = "list",
  garbage_collection = TRUE,
  memory = "transient"
)

tar_pipeline(
  tar_target(
    name = model_input,
    command = define_input(param),
    pattern = map(param)
  ),
  tar_target(
    name = other_model_input,
    command = different_input_function(other_param),
    pattern = map(param)
  ),
  tar_target(
    name = all_input,
    # I realize that I could also use tar_combine() from tarchetypes here
    command = purrr::splice(model_input, other_model_input)
  ),
  tar_target(
    name = all_input_list,
    command = all_input,
    pattern = map(all_input)
  ),
  tar_target(
    name = model_result,
    command = run_model(all_input_list),
    pattern = map(all_input_list)
  )
)
```

But, my lists are large files. And if I have too many branches, the `all_input` target does not fit in RAM.
I would like to be able to define the `all_input` target as a branched target that points to all the branches of `model_input` and all the branches of `other_model_input`.
We would not need to write anything in _targets/object, juste have a target that regroups two branched targets.
It could be defined as something like
```r
tar_target(
  name = all_input,
  command = tar_bind(model_input, other_model_input)
  # Maybe with tar_combine() with a new parameter to specify to not load the targets
)
tar_target(
  name = model_result,
  command = run_model(all_input),
  pattern = map(all_input)
)
```

Does it make sense? 
Does this already exist? 

A benefit of such a feature would be to easily add branches to a target without modifying the functions that generate the other branches and thus keep most branches synchronized.

I hope that this is clear and that it makes sense.

Thanks again for `targets`, it is really (work)life-changing.

**Comment by wlandau** [comment]
It is not possible to retroactively pool branches without creating a new target that loads them all into memory. In your case, I would recommend either

1. Do a `tar_map()` over the two sets of settings to make the pipeline more concise, or
2. Save the input as physical files and track the branches with `format = "file"` in `tar_target()`. That way, all the file paths would be loaded into memory when you combine them, but not the data itself.

**Comment by glep** [comment]
Ok, thanks!

I like solution 2. 
I thought about it and feared that it would be weird to store data outside or _targets/objects.
But if you suggest it, that is validation enough for me!
