### ISSUE TITLE
Feature Request: Automatic package-specific target suggestions

### ISSUE THREAD

**Issue by billdenney** [wlandau/targets#243]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [ ] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

I don't yet fully understand the rationale of package-specific targets (e.g. `stantargets`).  So, this may be invalid (or it may be better categorized as a question than a feature request, but here goes...).

It seems like the package-specific target finding effort may be non-trivial.  For instance, I know that `stantargets` exists, but others may not.  And, I think that it would help to have an auto-discovery mechanism.  For example, if I had a regular target that used `rstan` or `cmdstanr`, there would be a suggestion to use `stantargets`.

Overall, this seems like a hard problem.  How would you know of all the targets packages out there, and how would you detect if a pipeline used a specific package in a way that would be helpful?

A "simple" way to do this could be to have detection code in targets that would give a boolean response of "Is this running within a `targets` pipeline?"  If yes, then the main package (e.g. `cmdstanr`) could then detect "Is this running within `stantargets`?" in addition.  If the first was `TRUE` and the second was `FALSE`, then a message could come from the `cmdstan` package.  That requires that the person making `stantargets` can also make a change to `cmdstanr`, which isn't always true.  It would also make `targets` some level of dependency for all the main packages.

A harder way to do this would be that `targets` would detect all of the simple stuff and know about all the packages out there.  That seems like a huge amount of technical debt that is not likely to be a good idea.

**Comment by wlandau** [comment]
It is easier, more helpful, and more appropriate to provide such recommendations in the documentation. `stantargets` is now mentioned in the README files of both `targets` and [`targets-stan`](https://github.com/wlandau/targets-stan).
