### ISSUE TITLE
Integration with bash/snakemake (or make tar_make() run a custom script)?

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#247]
This feature, if not present, would be a "nice to have". I am documenting the idea here in case you find it useful - let me know if the frequent issues bother you!

Snakemake is a popular pipeline tool and I find it most useful with bash commands. In some projects I may need to switch between bash and R analysis. If the analysis sequence is R->bash->R, it would be nice if I can run a selected number of targets in a custom script. 

OK now I realise the easiest way to do it is perhaps to name all the targets that bash script depends on with the same suffix and run `tar_make(starts_with("suffix"))` in a R file that will be run by snakemake/bash scripts. I am going to close the issue after I raise it just for future reference.

**Comment by mattwarkentin** [comment]
Hi @liutiming,

Whenever I need to run some command-line tools, but I still want the results to eventually come back to `R` for other downstream analyses, I usually find that writing an `R` function is the best approach. It allows you to use the `targets` pipeline in all the same ways and keep everything self-contained.
```r
tar_pipeline(
  tar_target(
    step1,
    <<some R code>>
  ),
  tar_target(
    step2,
    cli_stuff()
  ),
  tar_target(
    step3,
    <<some more R code>>
  )
)
```
Where `cli_stuff()` can be anything you want, including something like...
```r
cli_stuff <- function(...) {
  processx::run(...) # this might return something meaningful via stdout or save something to disk
  # <<some R processing of whatever the CLI tool returns>>
  return(a_nice_R_object)
}
```
Now all of your bash/shell tasks play nicely with `targets`. Actually, the extra R processing of the CLI results could be its own step. If `cli_stuff()` saves a file to disk, you can just use the `format` arg to `tar_target` to identify it as an external file dependency. A downstream `target` can digest this file and process it as an entirely separate step.
```r
tar_pipeline(
  tar_target(
    step1,
    <<some R code>>
  ),
  tar_target(
    step2,
    cli_stuff(),
    format = "file"
  ),
  tar_target(
    step3,
    process_cli_results(step2)
  )
)
```

**Comment by wlandau** [comment]
I agree with @mattwarkentin, `processx` is super nice for working with command line tools in R. Whereas most pipeline tools have some sort of command line functionality so they can be reasonably language agnostic, `targets` deliberately works within the confines of an R session. This allows `targets` to make assumptions about R works and express those assumptions in nifty features: for example, the ability to implicitly detect dependency relationships among targets using static code analysis instead of having to explicitly declare them like in a `Makefile` recipe. So the more R-focused your project is, the less friction you will have on your end.

**Comment by liutiming** [comment]
That's very helpful, thank you @mattwarkentin @wlandau !

**Comment by liutiming** [comment]
Trying to get some wisdom here: https://github.com/r-lib/processx/issues/285

Do you encounter any issues with bioinformatics tools? @mattwarkentin

**Comment by mattwarkentin** [comment]
Hi @liutiming,

I don't think there would be any reason why `processx` would have issues with bioinformatics tools versus other CLI tools. I haven't run into any tool-specific issues as of yet. 

You may choose to use `system()` or `system2()`, if they suit your needs. `processx` is just a more full-featured and consistent API for running shell commands from `R`. Basically you just need to figure out how to translate from the way you submit the command in the shell to how `processx` expects the command.

**Comment by wlandau** [comment]
I agree. As long as the `processx`/`system()`/`system2()` process is blocking (so the target does not quit early) and you track the output files with `tar_target(format = "file")`, this should work.

**Comment by liutiming** [comment]
Thanks so much! really appreciate of your input!
