### ISSUE TITLE
Encoding issue on windows when running tar_make()

### ISSUE THREAD

**Issue by gorkang** [wlandau/targets#249]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

When running a function inside a targets pipeline that matches Spanish strings, I get inconsistent results depending on how I run the code (tar_make() vs line by line). This happened in two separate Windows computers.

So, for example, the string "Básica incompleta; primaria o preparatoria incompleta." will be correctly given the value 2 when running tar_make() in Ubuntu, but will be given the value 9999 when running tar_make() in Windows. To make it more interesting, if I run the function (in this case, `prepare_BUG()`, see below) line by line in Windows, I get the correct expected result.

```
prepare_BUG <- function() {

  # library(readr)
  # library(dplyr)
  
  DF = read_csv("data/DF.csv", 
                col_types = 
                  cols(
                    id = col_double(),
                    RAW = col_character()
                  ))
  
  DF %>% 
    select(id, RAW) %>% 
    mutate(
    DIR =
      case_when(
        RAW == "Sin estudios formales." ~ 1,
        RAW == "Básica incompleta; primaria o preparatoria incompleta." ~ 2,
        RAW == "Universitaria completa (carreras de 4 o más años); oficial de FFAA y Carabineros." ~ 3,
        TRUE ~ 9999
      )
  )

}
```

### Outputs of the `prepare_BUG()` function depending on how it is run
```

# Ubuntu tar_make() *Expected output* ---------------------------------------

# A tibble: 3 x 3
# id RAW                                                                                 DIR
# <dbl> <chr>                                                                             <dbl>
# 1     1 Sin estudios formales.                                                                1
# 2     2 Básica incompleta; primaria o preparatoria incompleta.                                2
# 3     3 Universitaria completa (carreras de 4 o más años); oficial de FFAA y Carabineros.     3



# Windows tar_make() ------------------------------------------------------

# A tibble: 3 x 3
# id RAW                                                                                 DIR
# <dbl> <chr>                                                                             <dbl>
# 1     1 Sin estudios formales.                                                                1
# 2     2 Básica incompleta; primaria o preparatoria incompleta.                             9999
# 3     3 Universitaria completa (carreras de 4 o más años); oficial de FFAA y Carabineros.  9999


# Windows Running prepare_BUG() line by line ------------------------------

# A tibble: 3 x 3
# id RAW                                                                                 DIR
# <dbl> <chr>                                                                             <dbl>
# 1     1 Sin estudios formales.                                                                1
# 2     2 Básica incompleta; primaria o preparatoria incompleta.                                2
# 3     3 Universitaria completa (carreras de 4 o más años); oficial de FFAA y Carabineros.     3

```

## Reproducible example

Here a minimal reproducible working example attached: [BUG.zip](https://github.com/wlandau/targets/files/5735217/BUG.zip)

## Expected result

Outputs should be consistent.

### Ubuntu

> R version 3.6.3 (2020-02-29)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.5 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=es_CL.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=es_CL.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=es_CL.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=es_CL.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
>  [1] igraph_1.2.6        rstudioapi_0.13     magrittr_2.0.1      tidyselect_1.1.0    prompt_1.0.0        gert_1.0.2          R6_2.5.0            rlang_0.4.9         fansi_0.4.1         stringr_1.4.0       targets_0.0.0.9003  tools_3.6.3         sys_3.4             parallel_3.6.3     
> [15] data.table_1.13.4   rprofile_0.1.4.9002 cli_2.2.0           withr_2.3.0         askpass_1.1         ellipsis_0.3.1      remotes_2.2.0       yaml_2.2.1          openssl_1.4.3       assertthat_0.2.1    digest_0.6.27       tibble_3.0.4        lifecycle_0.2.0     crayon_1.3.4       
> [29] processx_3.4.5      purrr_0.3.4         callr_3.5.1         codetools_0.2-18    ps_1.5.0            vctrs_0.3.6         credentials_1.3.0   clisymbols_1.2.0    memoise_1.1.0       glue_1.4.2          prettycode_1.1.0    stringi_1.5.3       compiler_3.6.3      pillar_1.4.7       
> [43] memuse_4.1-0        pkgconfig_2.0.3    

### Windows1

> R version 4.0.3 (2020-10-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
>  [1] igraph_1.2.6       rstudioapi_0.13    knitr_1.30         magrittr_2.0.1     tidyselect_1.1.0   here_1.0.1         R6_2.5.0           rlang_0.4.9       
>  [9] fansi_0.4.1        tools_4.0.3        targets_0.0.0.9003 DT_0.16            data.table_1.13.4  xfun_0.19          tinytex_0.28       cli_2.2.0         
> [17] withr_2.3.0        ellipsis_0.3.1     htmltools_0.5.0    remotes_2.2.0      rprojroot_2.0.2    yaml_2.2.1         digest_0.6.27      assertthat_0.2.1  
> [25] lifecycle_0.2.0    tibble_3.0.4       crayon_1.3.4       processx_3.4.5     purrr_0.3.4        callr_3.5.1        htmlwidgets_1.5.3  vctrs_0.3.6       
> [33] ps_1.5.0           codetools_0.2-16   glue_1.4.2         evaluate_0.14      rmarkdown_2.6      pillar_1.4.7       compiler_4.0.3     pkgconfig_2.0.3   

### Windows 2

Similar to Windows1, but with a different locale:

> "LC_COLLATE=English_Australia.1252;LC_CTYPE=English_Australia.1252;LC_MONETARY=English_Australia.1252;LC_NUMERIC=C;LC_TIME=English_Australia.1252"

**Comment by wlandau** [comment]
Thanks for the example, that allowed me to reproduce this locally on Windows 10. The problem is actually the encoding in `source()` in the `_targets.R` file. One solution is to run `source("R/prepare_BUG.R", encoding = "UTF-8")` instead of just `source("R/prepare_BUG.R")`. Another is to put `options(encoding = "UTF-8")` in the `.Rprofile` file of your project or your home directory.

**Comment by psychelzh** [comment]
Unfortunately, adding `options(encoding = "UTF-8")` to `.Rprofile` is not so helpful. Anyway, adding `encoding = "UTF-8"` to `source()` works very well. Thanks!
