### ISSUE TITLE
use `unlist` with pattern?

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#250]
Hi @wlandau , hope you had a good Christmas!

This is to let you know that when using `unlist` with pattern, the downstream targets will take ages to run. I sort of see this coming...

My solution is to create a target just for `unlist` and I thought it would be good to verify with you and let the rest know too

Of course that sort of violates the rule that each target should be large enough but I cannot find another better workaround :P

**Comment by wlandau** [comment]
Whenever performance issues like this arise, I find the most productive first steps are to profile the pipeline. This is usually the quickest and most informative way to gather evidence of what is causing the slowness. Then, if you can reproduce the issue in a simple example, you can post the code and the flame graphs. I wrote some [general guidance here](https://wlandau.github.io/targets-manual/practice.html#performance) using the [`proffer`](https://r-prof.github.io/proffer/) package.

Without empirical evidence, it's hard to say what could be causing the slowness. But what you describe sounds like a limitation that can arise if you have a large number of branches or each branch has a lot of data. If either explanation is correct, your profiling study may show a large bottleneck at `readRDS()` or similar function. If that is what you find, some potential workarounds might include the following.

1. Select an efficient storage format using the `format` argument of `tar_target()`.
2. Use [batching](https://wlandau.github.io/targets-manual/dynamic.html#batching) to reduce the number of dynamic branches.

**Comment by wlandau** [comment]
In HPC, if you gather lots of branches with `unlist()`, you might also encounter memory issues you did not see before, and parallel workers may fail silently (soon to be fixed in `clustermq`). If your compute nodes have less memory than the main process, you might try setting `deployment = "main"` in the target with `unlist()`.

**Comment by liutiming** [comment]
thank you very much!
