### ISSUE TITLE
Validate selected targets for once?

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#257]
Hi @wlandau, we had a related discussion at https://github.com/wlandau/targets/issues/246 so this might actually need to be a feature request.

This feature will be really helpful if I am just refactoring my code (e.g. renaming) so I know that no downstream results will change. But I do not want to use `tar_cue` since in the future this target's value may change, and invalidation will be necessary then.

**Comment by wlandau** [comment]
So if I understand correctly, the idea is to look at a target that is invalidated (i.e. going to run next time you call `tar_make()`) and force it to skip. I would rather stick with cues for this.

> But I do not want to use tar_cue since in the future this target's value may change, and invalidation will be necessary then.

Whenever you are ready to let the invalidation happen, you can remove the cue. If you have a lot of targets, this may require a lot of manual typing, but you can reduce most of the work by defining blocks of targets within calls to `tar_option_set()`.

``` r
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  tar_option_set(cue = tar_cue(mode = "always"))
  run_always <- list(
    tar_target(a, 1),
    tar_target(b, 1)
  )
  tar_option_set(cue = tar_cue())
  run_normally <- list(
    tar_target(c, 1),
    tar_target(d, 1)
  )
  list(run_always, run_normally)
})

tar_make()
#> ● run target a
#> ● run target b
#> ● run target c
#> ● run target d
#> ● end pipeline

tar_make()
#> ● run target a
#> ● run target b
#> ✓ skip target c
#> ✓ skip target d
#> ● end pipeline
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by liutiming** [comment]
nice that is a great idea! Thanks so much for suggesting that!
