### ISSUE TITLE
tar_visnetwork accept a target and plot upstream targets

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#259]
```
if (FALSE) { # Interactive only.
tar_dir({
tar_script({
  tar_option_set()
  list(
    tar_target(y1, 1 + 1),
    tar_target(y2, 1 + 1),
    tar_target(z, y1 + y2),
    tar_target(y3, y1 + 1),
  )
})
tar_visnetwork(target = z)
})
} 
```
result will contain y1, y2, z but not y3.

This will be very helpful for large projects so that we can just develop one branch at a time

**Comment by wlandau** [comment]
Similarly, users might want to look at a neighborhood of nodes, or everything downstream from one or more nodes. I [tried this with `drake`](https://books.ropensci.org/drake/visuals.html#subgraphs), but it was burdensome to maintain, and most of the functionality was not useful most of the time. I feel the existing `allow` and `exclude` arguments of `tar_visnetwork()` are more flexible, and `tidyselect` support adds a decent amount of convenience.

``` r
library(targets)
tar_script({
  list(
    tar_target(y1, 1 + 1),
    tar_target(y2, 1 + 1),
    tar_target(y3, y1 + 1),
    tar_target(z1, y1 + y2),
    tar_target(z2, y1 + y3)
  )
})

tar_visnetwork(exclude = starts_with("z"))
```

![](https://i.imgur.com/CoIo9Nh.png)

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by liutiming** [comment]
I see your point. It is good to know a bit about drake and I knew you must have thought about this feature before. 

Howe about allowing target lists to be passed to `allow` or `exclude`? Will that be equally cumbersome?

**Comment by wlandau** [comment]
Unfortunately, `targets` loses information about how targets are nested in lists once the pipeline object is constructed internally. I recommend `tidyselect`-friendly names.

**Comment by liutiming** [comment]
I see. How about just commenting out some targets lists to simplify the graph - especially convenient if someone loads the targets from distinct files.

**Comment by wlandau** [comment]
Sounds like a great user-side workaround to me.

**Comment by liutiming** [comment]
lovely. thank you and hope this would help others too!
