### ISSUE TITLE
using targets to combine parameterized RMarkdown documents with bookdown

### ISSUE THREAD

**Issue by robitalec** [wlandau/targets#261]
## Prework

* [X] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [X] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [X] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [X] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [X] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [X] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Just an update from https://github.com/ropensci/drake/issues/1337.
I ended up sorting out the framework for combining bookdown + targets + parameterized RMarkdown documents. 
I've wrapped it up as a MWE: https://github.com/robitalec/targets-parameterized-bookdown

`targets` handles this task really well, I can track changes in the template and index .Rmd files as well as use it for dynamic branches either for multiple files (as shown in the MWE) or it could adapted for groups within a dataset. 

Thanks for the great tool, much appreciated!

## Reproducible example

* [X] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [X] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [X] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [X] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

**Comment by wlandau** [comment]
Thanks for sharing, @robitalec! This looks like a great resource, and it might be able to help with https://github.com/wlandau/tarchetypes/issues/23 (FYI @tjmahr).
