### ISSUE TITLE
target fails to update when target and function have same name

### ISSUE THREAD

**Issue by rich-payne** [wlandau/targets#262]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

When a target and function have the same name, the function is not seen as a dependency of the target, and the target is not updated when the function is changed.

## Reproducible example

Contents of `_targets.R`:

```
library(targets)
targets::tar_option_set(packages = c("targets"))
x <- function(y) y
tar_target(x, x(3))
```

Run `tar_visnetwork()` and note that the function `x` is not listed.

Run `tar_make()` and the plan runs as expected (check with `tar_read(x)`).

Update contents of `_targets.R` by changing the function `x`

```
library(targets)
targets::tar_option_set(packages = c("targets"))
x <- function(y) y^2
tar_target(x, x(3))
```

Run `tar_make()`, and the target `x` is not updated.

## Expected result

The target `x` should be updated when function `x` is changed.

## Diagnostic information

* The [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity): 95acfafc8ae504512e3fcf0abe4758f5ddb4270e

Session Info: 
![image](https://user-images.githubusercontent.com/39996197/103930371-9e1aea00-50ec-11eb-83a7-61d61f3c53ef.png)

**Comment by wlandau** [comment]
The best I can do is throw a suppressable warning when there are name conflicts. Should be implemented now.

Targets and functions must have unique names. All `targets` sees is the command, and it cannot automatically know whether the user wants to use the dependency in the pipeline or the dependency in the environment. Consider pipeline A:

```r
library(targets)
library(purrr)
x <- function(y) y
list(
  tar_target(x, 1:3),
  tar_target(y, map(1:3, x))
)
```

and pipeline B:

```r
library(targets)
library(purrr)
x <- function(y) y
list(
  tar_target(x, 1:3),
  tar_target(y, map(x, identity)) # key difference
)
```

In pipeline A, we want the function `x`. But in pipeline B, we want the target `x`. There is no static code analysis that can distinguish between the two scenarios in the general case.
