### ISSUE TITLE
Topo sort the rows of tar_manifest()

### ISSUE THREAD

**Issue by wlandau** [wlandau/targets#263]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/wlandau/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

From @sctyner, ref: https://twitter.com/sctyner/status/1347226231889137666

**Comment by wlandau** [comment]
Also added some safeguards around internal calls to `igraph::topo_sort()`. We should always use `as.character(igraph::topo_sort(igraph)$name)` instead of `as.character(names(igraph::topo_sort(igraph)))`, and the `return.vs.es` `igraph` option must be `TRUE` during topo sort.

**Comment by sctyner** [comment]
Thanks @wlandau!
