### ISSUE TITLE
Automatic resizing of dependency graph when first loaded

### ISSUE THREAD

**Issue by mattwarkentin** [wlandau/targets#264]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/wlandau/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

Hi @wlandau,

Is there any way to have the dependency graph, as generated by `tar_visnetwork()`, always appear in the `Viewer` window zoomed-out enough so the whole graph is visible? It seems that, by default, the graph is sort of zoomed in on the centroid of the graph and I can either: 

1) Manually zoom out

2) Any slight resizing of the Viewer window triggers the graph to be presented in full view.

Every time I call `tar_visnetwork()` I have to slightly resize the Viewer pane to get the graph in full view. Similarly, I have started using `tar_watch()` to monitor the graph while running `tar_make()`, and the graph in the shiny app suffers from the same fate, which means, even though it updates the graph, often I can't even see which nodes are running or completed until I manually change the zoom/FOV.

Thoughts?

**Comment by wlandau** [comment]
Fortunately, I was able to fix this with `visPhysics(stabilization = FALSE)`. Didn't expect to get that lucky. Related: https://github.com/datastorm-open/visNetwork/issues/46.

**Comment by mattwarkentin** [comment]
If I haven't said it already, `tar_watch()` is such an amazing addition!

**Comment by mattwarkentin** [comment]
Side note, in case it is of interest to you or others (based on @ginolhac's presentation), using the following code in your `run.R` script and setting it up as a custom build script will open the dashboard in a browser, build the pipeline and show updates in the `Build` pane, and then shut down the dashboard when the pipeline finishes. It's a nice workflow, I must say.
```r
#!/usr/local/bin/Rscript 
targets::tar_watch(targets_only = TRUE, verbose = FALSE)
targets::tar_make_clustermq(
  reporter = "timestamp",
  workers = 4L
)
```

**Comment by wlandau** [comment]
Cool! Maybe one for [`tarflow`](https://github.com/toddgrabowsky/tarflow)? cc @toddgrabowsky,  @sctyner, @petrbouchal (#258).
