### ISSUE TITLE
Is second element in `map` treated as a list?

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets#266]
I realised that in `pattern = map(a,b)`, where `a` and `b` are lists, `a` is sent as a list but `b` is sent in as an element (i.e. `b[[i]]` instead of `b[i]`). Is this the designed behaviour (because this is how `purrr` works)? 

This was rather unexpected because I was expecting both to be a list and used `pluck()` for both `a` and `b` in the function. 

Happy to produce a reprex if needed.

**Comment by wlandau** [comment]
The `iteration` setting controls how `a` and `b` are passed. You can set this locally in `tar_target()` or globally with `tar_option_set()`. The default `iteration = "vector"` is based on the `vctrs` package, which tries to make automatic judgements about how to slice targets for branching. Details: https://wlandau.github.io/targets-manual/dynamic.html#iteration

``` r
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  list(
    tar_target(a, list(1, 2), iteration = "list"),
    tar_target(b, list(3, 4), iteration = "list"),
    tar_target(c, list(a = a, b = b), pattern = map(a, b), iteration = "list")
  )
})

tar_make()
#> ● run target a
#> ● run target b
#> ● run branch c_c4546e89
#> ● run branch c_bb0cb6e1
#> ● end pipeline

str(tar_read(c, branches = 1)[[1]])
#> List of 2
#>  $ a: num 1
#>  $ b: num 3

tar_script({
  options(crayon.enabled = FALSE)
  list(
    tar_target(a, list(1, 2), iteration = "vector"),
    tar_target(b, list(3, 4), iteration = "list"),
    tar_target(c, list(a = a, b = b), pattern = map(a, b), iteration = "list")
  )
})

tar_make()
#> ● run target a
#> ✓ skip target b
#> ● run branch c_fe546f40
#> ● run branch c_51569be6
#> ● end pipeline

str(tar_read(c, branches = 1)[[1]])
#> List of 2
#>  $ a:List of 1
#>   ..$ : num 1
#>  $ b: num 3
```

<sup>Created on 2021-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by liutiming** [comment]
Ah yes thanks for the reprex. I was aware of `iteration` but I think what was unclear to me was that I need to indicate that in every list upstream to the target that I need to run `pattern`.

``` r
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  tar_pipeline(list(
    tar_target(a, list(data.frame(c = 1), data.frame(c = 2))),
    tar_target(b, list(data.frame(c = 3), data.frame(c = 4)), iteration = "list"),
    tar_target(c, 
               {
                 print("a")
                 print(str(a))
                 print("b")
                 print(str(b))
               }, 
               pattern = map(a, b), 
               iteration = "list")
  )
  )
})

tar_make()
#> * run target a
#> * run target b
#> * run branch c_e1a5b493
#> [1] "a"
#> List of 1
#>  $ :'data.frame':    1 obs. of  1 variable:
#>   ..$ c: num 1
#> NULL
#> [1] "b"
#> 'data.frame':    1 obs. of  1 variable:
#>  $ c: num 3
#> NULL
#> * run branch c_e2f83374
#> [1] "a"
#> List of 1
#>  $ :'data.frame':    1 obs. of  1 variable:
#>   ..$ c: num 2
#> NULL
#> [1] "b"
#> 'data.frame':    1 obs. of  1 variable:
#>  $ c: num 4
#> NULL
```

<sup>Created on 2021-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by liutiming** [comment]
BTW, Happy to see it has been peer reviewed! Hope this will draw more attention to targets :)

**Comment by wlandau** [comment]
> BTW, Happy to see it has been peer reviewed! 

So am I! `targets` will go to CRAN as soon as the logistical pieces of https://github.com/ropensci/software-review/issues/401 have completed.
